Git y GitHub en RStudio
IslasGECI/islasgeci.github.io pull request #101
Opened 2022-05-10 16:08 UTC by LizethMReyes

Agregamos el primer borrador.

2022-06-01 15:56 UTC, nepito commented
Aquí debemos empezar con [codewars](https://www.codewars.com/)

2022-06-03 20:49 UTC, devarops commented
@LizethMReyes ¿Ya podemos revisar este PR?

2022-06-06 20:36 UTC, LizethMReyes commented
Hola, hola, ya termine las notas de [Git y GitHub en RStudio](https://github.com/IslasGECI/seleccion_analista_2022_lmrg/issues/29). Espero sus comentarios.

2022-06-06 20:46 UTC, devarops commented
Sólo veo una única consignación. ¿Eso es correcto?

2022-06-06 20:47 UTC, devarops requested changes
Se ve muy bien, @LizethMReyes. ¡Felicidades!

¿Por favor podrías usar un máximo de 100 caracteres por línea?

2022-06-06 23:50 UTC, LizethMReyes commented
¡Listo!

2022-06-06 23:51 UTC, LizethMReyes commented
> Sólo veo una única consignación. ¿Eso es correcto?

Sip, este Pull Request esta asociado a solo una consignación

2022-06-07 01:23 UTC, devarops commented
@LizethMReyes Por favor podrías presionar el botón _Re-request review_?

2022-06-07 03:53 UTC, devarops requested changes
Las líneas tienen más de 100 caracteres. Por favor separa cada línea en múltiples líneas de menos de 100 caracteres cada una. Yo hice la primera línea como ejemplo. Sigue ese ejemplo para corregir el resto de la líneas.

2022-06-07 03:53 UTC, devarops commented on _posts/2022-05-10-github_rstudio.md
> +Docker es una aplicación de software para crear, empaquetar y distribuir aplicaciones de forma más rápida en forma de contenedores dentro de su propio entorno de ejecución. Un punto importante a dest
Esta línea tiene más de 100 caracteres. Por favor separa la línea en múltiples líneas de menos de 100 caracteres cada una:

```suggestion
Docker es una aplicación de software para crear, empaquetar y distribuir aplicaciones de forma más
rápida en forma de contenedores dentro de su propio entorno de ejecución. Un punto importante a
destacar, es que permite empaquetar una aplicación con todas sus dependencias para ser ejecutada en
cualquier plataforma. Durante este curso propedéutico es importante aprender sobre el uso de esta
herramienta para poder colaborar con el equipo de Data Analysis GECI.

```

2022-06-08 01:11 UTC, LizethMReyes commented
Ya lo volví a modificar, ¿si esta de la forma correcta?

2022-06-08 01:44 UTC, devarops requested changes
Aquí te dejo un par de comentarios

2022-06-08 01:44 UTC, devarops commented on _posts/2022-05-10-github_rstudio.md
> +<img width="745" alt="Captura de Pantalla 2022-05-05 a la(s) 1 14 16" src="https://user-images.githubusercontent.com/87685163/166871596-3489f0f8-2b9b-4842-a2a1-09ee95ed19b9.png">
En el resto de la imágenes agregaste un bloque de la siguiente manera:

```suggestion

> <img width="745" alt="Captura de Pantalla 2022-05-05 a la(s) 1 14 16" src="https://user-images.githubusercontent.com/87685163/166871596-3489f0f8-2b9b-4842-a2a1-09ee95ed19b9.png">
```

Por sonsistencia, por favor agrégalo aquí también o remuévelo del resto.

2022-06-08 01:44 UTC, devarops commented on _posts/2022-05-10-github_rstudio.md
> +> <img width="396" alt="Captura de Pantalla 2022-05-05 a la(s) 1 43 10" src="https://user-images.githubusercontent.com/87685163/166874527-297b24d6-40e2-485f-b3da-339d3e479090.png">
En la primer figura no agregaste el `>` antes de la imagen. Por consistencia, quita el `>` de esta figura y el resto, o agregala a la primera.

```suggestion
<img width="396" alt="Captura de Pantalla 2022-05-05 a la(s) 1 43 10" src="https://user-images.githubusercontent.com/87685163/166874527-297b24d6-40e2-485f-b3da-339d3e479090.png">
```

2022-06-08 03:30 UTC, LizethMReyes commented
No estaba prestando atención a las capturas de pantalla hasta ahora. Hay dos versiones, aquí donde estamos haciendo los cambios es para clonar un repositorio con URL y el otro que subí apenas es con SSH, ¿nos vamos a quedar con ambos?

2022-06-08 13:47 UTC, devarops commented
> No estaba prestando atención a las capturas de pantalla hasta ahora. Hay dos versiones, aquí donde estamos haciendo los cambios, es para clonar un repositorio con [HTTPS](https://github.com/LizethMReyes/islasgeci.github.io/blob/feature/github_rstudio/_posts/2022-05-10-github_rstudio.md) y el otro que subí apenas es con [SSH](https://github.com/IslasGECI/seleccion_analista_2022_lmrg/issues/29), ¿nos vamos a quedar con ambos?

No, por favor deja solo con SSH. (Quita el ejemplo con HTTPS.)

2022-06-08 13:48 UTC, devarops requested changes
En el ejemplo para clonar un repo usa SSH en lugar de HTTPS.

2022-06-08 15:32 UTC, LizethMReyes commented
Esta bien, en la tarde hago el cambio. :)

2022-06-23 16:00 UTC, devarops requested changes
Vamos avanzando.

2022-06-23 16:00 UTC, devarops commented on _posts/2022-05-10-github_rstudio.md
> +Nos permite empaquetar una aplicación con todas sus dependencias para ser ejecutada en cualquier
```suggestion
Docker nos permite empaquetar una aplicación con todas sus dependencias para ser ejecutada en cualquier
```

2022-06-23 16:00 UTC, devarops commented on _posts/2022-05-10-github_rstudio.md
> +En el equipo de Ciencia de Datos GECI usamos esta herramienta para trabajar. Es una herramienta
```suggestion
En el equipo de Ciencia de Datos en GECI usamos esta herramienta para reproducir nuestros análisis. Es una herramienta 
```

2022-06-23 16:00 UTC, devarops commented on _posts/2022-05-10-github_rstudio.md
> +Anteriormente, instalamos Docker en Mac con la siguiente línea en la terminal:
```suggestion
Anteriormente, instalamos Docker en macOS con la siguiente línea en la terminal:
```

2022-06-23 16:00 UTC, devarops commented on _posts/2022-05-10-github_rstudio.md
> +En MacOs es necesario abrir la app desde la lista de aplicaciones haciendo clic
```suggestion
En macOS es necesario abrir la app desde la lista de aplicaciones haciendo clic 
```

2022-06-23 16:00 UTC, devarops commented on _posts/2022-05-10-github_rstudio.md
> +Git es un sistema de control de versiones. Realiza seguimiento de los cambios de código y
```suggestion
Git es un sistema de control de versiones. Git realiza seguimiento de los cambios de código y 
```

2022-06-23 16:00 UTC, devarops commented on _posts/2022-05-10-github_rstudio.md
> +formas de usar git. Desde la línea de comandos, utilizar RStudio o utilizar una app independiente
```suggestion
formas de usar Git. Desde la línea de comandos, utilizar RStudio o utilizar una app independiente 
```

2022-06-23 16:00 UTC, devarops commented on _posts/2022-05-10-github_rstudio.md
> +dedicado a la computación estadística y gráficos. Incluye una consola, herramientas para
```suggestion
dedicado a la computación estadística y gráficos. RStudio incluye una consola, herramientas para 
```

2022-06-23 16:00 UTC, devarops commented on _posts/2022-05-10-github_rstudio.md
> +Antes de comenzar a crear la llave primero revisaremos que no hay ninguna llave generada
¿A cuál llave te refieres?

2022-06-23 16:00 UTC, devarops commented on _posts/2022-05-10-github_rstudio.md
> +Después, vamos a crear nuestra llave ejecutando el siguiente comando `$ssh -keygen`. En seguida,
```suggestion
Después, vamos a crear nuestra llave ejecutando el siguiente comando `ssh-keygen`. En seguida, 
```

```suggestion
Después, vamos a crear nuestra llave ejecutando el siguiente comando `$ ssh-keygen`. En seguida, 
```

2022-06-23 16:00 UTC, devarops commented on _posts/2022-05-10-github_rstudio.md
> +a la configuración por default y ver cómo este cambia cuando hemos asignado un proyecto,
```suggestion
a la configuración por _default_ y ver cómo este cambia cuando hemos asignado un proyecto,
```

2022-07-27 19:59 UTC, LizethMReyes commented
Atendí las sugerencias y agrega subtítulos para separar mejor el contenido cómo me recomendó Mario y revisé la redacción con los comentarios que me hizo Memo, pero aún faltaría revisarlo otra vez. También, agregue un resumen en forma de tabla si es demasiado se podría quitar no hay problema.

2022-08-02 16:29 UTC, devarops requested changes
Aquí te dejo unas sugerencias.

2022-08-02 16:29 UTC, devarops commented on _posts/2022-05-10-github_rstudio.md
> +en el botón derecho en la opción _abrir_. Esto solo se hace una vez para finalizar
```suggestion
en el botón derecho en la opción _abrir_. Esto lo hacemos solo una vez para finalizar 
```

2022-08-02 16:29 UTC, devarops commented on _posts/2022-05-10-github_rstudio.md
> +la instalación y que reconozca la aplicación en la terminal.
> "que reconozca"

¿Quién reconoce?

2022-08-02 16:29 UTC, devarops commented on _posts/2022-05-10-github_rstudio.md
> +comparte esos cambios con otros, ya que permite que estos cambios se fusionen. Existen diferentes
```suggestion
comparte esos cambios con otros, ya que nos permite fusionar estos cambios. Existen diferentes 
```

2022-08-02 16:29 UTC, devarops commented on _posts/2022-05-10-github_rstudio.md
> +siguiente comando `$cat ~/.ssh/id_rsa.pub`. Copiamos desde **'ssh...** hasta la terminación
Esta instrucción se ve diferente al resto:

```suggestion
siguiente comando `cat ~/.ssh/id_rsa.pub`. Copiamos desde **'ssh...** hasta la terminación
```

```suggestion
siguiente comando `$ cat ~/.ssh/id_rsa.pub`. Copiamos desde **'ssh...** hasta la terminación
```

2022-08-02 16:29 UTC, devarops commented on _posts/2022-05-10-github_rstudio.md
> +Esto significa que estos archivos no tienen ningun seguimiento dentro de nuestro repositorio y
```suggestion
Esto significa que estos archivos no tienen ningún seguimiento dentro de nuestro repositorio y
```

2022-08-03 17:26 UTC, nepito approved these changes
LGtM

2022-08-03 17:29 UTC, merged