📝 Adding first step essay
IslasGECI/islasgeci.github.io pull request #107
Opened 2023-04-24 20:15 UTC by siduartep

Adding the first paragraph of the essay.

2023-04-24 23:55 UTC, devarops commented
@siduartep: Muchas gracias por crear este PR.

![giphy](https://user-images.githubusercontent.com/3461018/234139814-1ba8209f-6919-4c64-ad6c-6fcf6c248328.gif)

2023-04-26 17:44 UTC, devarops requested changes
Por favor, ¿podrías iniciar cada oración en su propia línea?

2023-04-26 21:00 UTC, devarops requested changes
Muchas gracias, @siduartep. Aquí te dejo algunos comentarios.

2023-04-26 21:00 UTC, devarops commented on _posts/2023-04-24-ensayo_siduartep.md
> +Cuando hablamos de reproducibilidad de resultados, nos referimos a la habilidad de repetir y obtener los mismos resultados utilizando los mismos datos y métodos de un estudio anterior.
Esta oración tiene 28 palabras. Por favor podrías verificar que cada oración tenga no más de 25 palabras?

2023-04-26 21:00 UTC, devarops commented on _posts/2023-04-24-ensayo_siduartep.md
> +Si no se pueden replicar los resultados, es imposible saber si son válidos o si se deben a errores en la recolección o análisis de los datos.
Esta oración tiene 27 palabras. Por favor podrías verificar que cada oración tenga no más de 25 palabras?

2023-04-26 21:00 UTC, devarops commented on _posts/2023-04-24-ensayo_siduartep.md
> +Para alcanzar estos resultados es necesario una sintonía entre las versiones de los datos, el entorno y el código. Dentro de las posibles herramientas para lograrlo se destaca Docker, el cual es un s
Esta oración tiene 55 palabras. Por favor podrías verificar que cada oración tenga no más de 25 palabras?

2023-04-26 21:00 UTC, devarops commented on _posts/2023-04-24-ensayo_siduartep.md
> +En nuestra práctica dentro del equipo de ciencia de datos, utilizamos la técnica de unit testing para asegurarnos de que cada componente individual de nuestro sistema funcione adecuadamente.
Esta oración tiene 28 palabras. Por favor podrías verificar que cada oración tenga no más de 25 palabras?

2023-04-26 21:00 UTC, devarops commented on _posts/2023-04-24-ensayo_siduartep.md
> +En lugar de probar todo el modelo de aprendizaje-automático, nos enfocamos en probar cada componente individual del modelo como la limpieza, transformación de datos, selección de características y ev
Esta oración tiene 31 palabras. Por favor podrías verificar que cada oración tenga no más de 25 palabras?

2023-04-26 21:00 UTC, devarops commented on _posts/2023-04-24-ensayo_siduartep.md
> +El proceso consta de tres pasos: primero, definimos los requisitos que debe cumplir el código de producción, luego creamos las pruebas y finalmente comprobamos si los resultados son correctos o incor
Esta oración tiene 31 palabras. Por favor podrías verificar que cada oración tenga no más de 25 palabras?

2023-04-26 21:00 UTC, devarops commented on _posts/2023-04-24-ensayo_siduartep.md
> +La aplicación de esta técnica en ciencia de datos puede mejorar la calidad y reproducibilidad de nuestros modelos, así como aumentar nuestra confianza en los resultados del análisis de datos.
Esta oración tiene 30 palabras. Por favor podrías verificar que cada oración tenga no más de 25 palabras?

2023-04-26 21:00 UTC, devarops commented on _posts/2023-04-24-ensayo_siduartep.md
> +Además, al tener la seguridad de que cada componente individual funcione adecuadamente, podemos identificar errores específicos en el modelo y corregirlos antes de implementarlo en un entorno de prod
Esta oración tiene 29 palabras. Por favor podrías verificar que cada oración tenga no más de 25 palabras?

2023-04-26 21:00 UTC, devarops commented on _posts/2023-04-24-ensayo_siduartep.md
> +En nuestra práctica, escribimos las pruebas antes de escribir el código, lo que asegura que el análisis se ha diseñado para cumplir con los requisitos establecidos por el usuario.
Esta oración tiene 29 palabras. Por favor podrías verificar que cada oración tenga no más de 25 palabras?

2023-04-26 21:00 UTC, devarops commented on _posts/2023-04-24-ensayo_siduartep.md
> +Además, existe una variante de TDD llamada Ping Pong Programming, en la cual dos programadores trabajan juntos en el mismo proyecto, alternándose para escribir las pruebas y el código.
Esta oración tiene 29 palabras. Por favor podrías verificar que cada oración tenga no más de 25 palabras?

2023-04-26 21:00 UTC, devarops commented on _posts/2023-04-24-ensayo_siduartep.md
> +En nuestro caso, las pruebas son diseñadas para verificar la calidad de los datos, la efectividad del modelo y la precisión de los resultados, lo que lleva a modelos más sólidos y confiables.
Esta oración tiene 33 palabras. Por favor podrías verificar que cada oración tenga no más de 25 palabras?

2023-04-26 21:00 UTC, devarops commented on _posts/2023-04-24-ensayo_siduartep.md
> +Este enfoque implica la ejecución de una serie de prácticas que abarcan desde el desarrollo, entrega, feedback y gestión de calidad de manera simultánea y constante.
Esta oración tiene 26 palabras. Por favor podrías verificar que cada oración tenga no más de 25 palabras?

2023-04-28 20:15 UTC, devarops requested changes
Vas muy bien. Ya casi queda.

2023-04-28 20:15 UTC, devarops commented on _posts/2023-04-24-ensayo_siduartep.md
> +Dentro de las posibles herramientas para lograrlo se destaca Docker, el cual es un software que dentro de sus funciones busca controlar versiones.
¿Docker controla las versiones de qué?

2023-04-28 20:15 UTC, devarops commented on _posts/2023-04-24-ensayo_siduartep.md
> +En nuestra práctica dentro del equipo, utilizamos la técnica de unit testing para asegurarnos de que cada componente individual de nuestro sistema funcione adecuadamente.
Usemos itálicas para las palabras en inglés.
```suggestion
En nuestra práctica dentro del equipo, utilizamos la técnica de _unit testing_ para asegurarnos de que cada componente individual de nuestro sistema funcione adecuadamente.
```

2023-04-28 20:15 UTC, devarops commented on _posts/2023-04-24-ensayo_siduartep.md
> +La colaboración entre los miembros del equipo en Ping-Pong-Programming también ha promovido una mejor comprensión del modelo y los datos subyacentes.
Creo que el segundo guión sobra.
```suggestion
La colaboración entre los miembros del equipo en _Ping-Pong Programming_ también ha promovido una mejor comprensión del modelo y los datos subyacentes.

```

2023-04-28 20:15 UTC, devarops commented on _posts/2023-04-24-ensayo_siduartep.md
> +La aplicación en conjunto de TDD y Ping-Pong-Programming en nuestro equipo ha llevado a una mayor calidad y mantenibilidad de nuestros análisis.
El segundo guión sobra:
```suggestion
La aplicación en conjunto de TDD y _Ping-Pong Programming_ en nuestro equipo ha llevado a una mayor calidad y mantenibilidad de nuestros análisis.

```

2023-04-28 20:15 UTC, devarops commented on _posts/2023-04-24-ensayo_siduartep.md
> +Además, estas técnicas han promovido una mejor comunicación y colaboración entre los miembros del equipo.
Esto es voz pasiva. ¿Por favor podrías cambiarlo a voz activa?

2023-04-28 20:15 UTC, devarops commented on _posts/2023-04-24-ensayo_siduartep.md
> +En cuanto a la colaboración, hemos adoptado la técnica de Ping Pong Programming, en la que dos desarrolladores trabajan juntos en el mismo proyecto.
```suggestion
En cuanto a la colaboración, hemos adoptado la técnica de _Ping-Pong Programming_, en la que dos desarrolladores trabajan juntos en el mismo proyecto.

```

2023-04-28 20:15 UTC, devarops commented on _posts/2023-04-24-ensayo_siduartep.md
> +El uso de unit testing y test driving development nos ha permitido garantizar que nuestro código funciona correctamente y cumpla con los requisitos del equipo.
```suggestion
El uso de _unit testing_ y _test driving development_ nos ha permitido garantizar que nuestro código funciona correctamente y cumpla con los requisitos del equipo.

```

2023-05-05 18:23 UTC, devarops requested changes
Ya casi terminamos. Aqui te dejo un par de comentarios.

2023-05-05 18:23 UTC, devarops commented on _posts/2023-04-24-ensayo_siduartep.md
> +tags: ensayo
Debemos escoger algo de [esta lista](https://github.com/IslasGECI/islasgeci.github.io/blob/develop/_data/tags.yml), por ejemplo:

```suggestion
tags: equipo

```

2023-05-05 18:23 UTC, devarops commented on _posts/2023-04-24-ensayo_siduartep.md
> +En cuanto a la colaboración, hemos adoptado la técnica de _Ping Pong Programming_, en la que dos desarrolladores trabajan juntos en el mismo proyecto.
Arriba ya definimos PPP, entonces aquí ya podemos usar esta abreviatura:

```suggestion
En cuanto a la colaboración, hemos adoptado la técnica de _PPP_, en la que dos desarrolladores trabajan juntos en el mismo proyecto.

```

2023-05-05 19:00 UTC, nepito requested changes
Aquí te dejo la primera tanda @siduartep

2023-05-05 19:00 UTC, nepito commented on _posts/2023-04-24-ensayo_siduartep.md
> +Cuando hablamos de reproducibilidad, nos referimos a la habilidad de repetir obteniendo los mismos resultados utilizando los mismos datos y métodos de un estudio anterior.
Aquí trataremos de utilizar menos palabras. En la parte "repetir obteniendo", _casi_ no aporta la palabra repetir. Así podríamos poner: 
```suggestion
Cuando hablamos de reproducibilidad, nos referimos a la habilidad de obtener los mismos resultados utilizando los mismos datos y métodos de un estudio anterior.
```
Esto es artesanal y hay de gustos a gustos. Por ejemplo ChatGPT propone:
> La reproducibilidad implica obtener los mismos resultados al utilizar los mismos datos y métodos de un estudio anterior.

Por favor cambia el enunciado utilizando un verbo (repetir u obtener) en lugar de dos (repetir y obtener).

2023-05-05 19:00 UTC, nepito commented on _posts/2023-04-24-ensayo_siduartep.md
> +Si no se pueden replicar los resultados, es imposible saber si son válidos o si se deben a errores en la recolección o el análisis.
Por favor mantengamos en la manera de lo posible la estructura: sujeto + verbo + predicado. Podemos tener el sujeto de manera implícita pero que esté: 
```suggestion
Si no podemos replicar los resultados, es imposible saber si son válidos o si se deben a errores en la recolección o el análisis.

```
En esta opción sabemos que el sujeto es la primera persona del plurar: nosotros. En la versión original es un poco más complicado.

2023-05-12 19:02 UTC, nepito reviewed
Hola @siduartep aquí te dejo otra tanda de revisiones.

2023-05-12 19:02 UTC, nepito commented on _posts/2023-04-24-ensayo_siduartep.md
> +_Docker_ es una herramienta útil al ser un _software_ que controla las dependencias necesarias para la ejecución de los análisis.
Creo que podemos ganar legibilidad quitando que el un _software_:
```suggestion
_Docker_ es una herramienta útil que controla las dependencias necesarias para la ejecución de los análisis.

```
Por favor simplifica la redacción.

2023-05-12 19:02 UTC, nepito commented on _posts/2023-04-24-ensayo_siduartep.md
> +Teniendo el control del ambiente a través de contenedores, conduce a la reproducibilidad.
Vamos a tratar de escribir en la forma: sujeto + verbo + predicado. 
Cuando empezamos con "Teniendo" no me queda claro el sujeto y el verbo "conduce" no sé a quién pertenece. La siguiente forma tal vez quede más clara:
```suggestion
El control del ambiente conduce a la reproducibilidad a través de contenedores.
```
Por favor en la manera de lo posible tratemos de eguir la estructura sujeto + verbo + predicado.

2023-05-12 19:02 UTC, nepito commented on _posts/2023-04-24-ensayo_siduartep.md
> +La aplicación de esta técnica puede mejorar la calidad y reproducibilidad de nuestros modelos, así como aumentar nuestra confianza en los resultados del análisis.
Vamos a ser valientes y decirlo con más convicción:
```suggestion
La aplicación de esta técnica mejora la calidad y reproducibilidad de nuestros modelos, también aumenta nuestra confianza en los resultados del análisis.

```

2023-05-12 19:02 UTC, nepito commented on _posts/2023-04-24-ensayo_siduartep.md
> +Además, existe una variante de _TDD_ llamada _Ping-Pong Programming (PPP)_, donde dos analistas trabajan en el mismo proyecto, alternándose para escribir pruebas y código.
Aquí trataré de cambiar el enunciado a la forma sujeto+verbo+predicado (svp):
```suggestion
_Ping-Pong Programming (PPP)_ es una variante del _TDD_  donde dos analistas trabajan en el mismo proyecto, alternándose para escribir pruebas y código.

```

2023-05-12 19:02 UTC, nepito commented on _posts/2023-04-24-ensayo_siduartep.md
> +Las pruebas son diseñadas para verificar la calidad de datos, efectividad del modelo y precisión en resultados, conduciendo a modelos más sólidos y confiables.
Aquí trataré de cambiar el enunciado a la forma  svp. Perderé un poco de precisión, pero espero ganar legibilidad:
```suggestion
Las pruebas verifican la calidad de los datos, la efectividad del modelo y la precisión en resultados, conduciendo a modelos más sólidos y confiables.

```
Agregué los artículos porque me sonó mejor. ¿Cómo la ves, deberíamos de quitarlos?

2023-05-17 20:12 UTC, nepito reviewed
@siduartep aquí va otra tanda

2023-05-17 20:12 UTC, nepito commented on _posts/2023-04-24-ensayo_siduartep.md
> +Posteriormente, se realiza una fase de pruebas automatizadas para evaluar la calidad del modelo, asegurándonos de que cumpla con los criterios definidos.
Cambiaremos a la primera persona del plural:
```suggestion
Posteriormente, realizamos una fase de pruebas automatizadas para evaluar la calidad del modelo, asegurándonos de que cumpla con los criterios definidos.

```

2023-05-17 20:12 UTC, nepito commented on _posts/2023-04-24-ensayo_siduartep.md
> +La documentación detallada de los pasos necesarios para generar los resultados, la separación clara entre código-datos, y la integración de resultados en un informe automatizado.
Creo que este enunciado no está terminado. Solo veo sujetos:
- La documentación detallada de los pasos necesarios para generar los resultados, 
- la separación clara entre código-datos, 
- y la integración de resultados en un informe automatizado.

No sé qué proponerte 🤪.

2023-05-19 17:50 UTC, nepito requested changes
Aquí va otra tanda

2023-05-19 17:50 UTC, nepito commented on _posts/2023-04-24-ensayo_siduartep.md
> +Lo que fomenta la comunicación constante entre el equipo y mejorando la comprensión del modelo.
Creo que este enunciado no está terminado. No estoy seguro de quién es el sujeto y quien el verbo. 

Se me ocurre el sujeto está implícito en el inicio del enunciado: "**Lo que** fomenta... ". Algo así como: "**Lo anterior** fomenta la comu...". Pero también pudiera ser que el que "sujeto" aun no llegue: "Lo que fomenta...del modelo **es** blablabla".

Por favor cambia el enunciado para quitarle lo ambiguo.

2023-05-19 17:50 UTC, nepito commented on _posts/2023-04-24-ensayo_siduartep.md
> +Como la falta de reproducibilidad, la introducción de errores, la dificultad para colaborar en equipo y la lentitud en el proceso de desarrollo.
Creo que este enunciado no está terminado. No estoy seguro de quién es el sujeto y quien el verbo.

Por favor cambia el enunciado para quitarle lo ambiguo.

2023-05-19 17:50 UTC, nepito commented on _posts/2023-04-24-ensayo_siduartep.md
> +Aunque indiscutiblemente, los resultados que trae consigo sopesan las dificultades para implementar estas técnicas conduciendo hacia un mejor entendimiento de nuestros datos.
Me parece un enunciado complicado. Te propondo patirlo en dos. Una opción podría ser:
```suggestion
Estas técnicas nos conducen hacia un mejor entendimiento de nuestros datos.
Indiscutiblemente, estos resultados sopesan las dificultades para implementar estás técnicas.

```

2023-06-02 17:30 UTC, nepito requested changes
Listo @siduartep :raised_hands: . Aquí te dejo una última sugerencia.

2023-06-02 17:30 UTC, nepito commented on _posts/2023-04-24-ensayo_siduartep.md
> +Indiscutiblemente, estos resultados sopesan las dificultades para implementar estás técnicas.
Voy a cambiar el orden solo para que agrupar las cosas negativas y las positivas:
```suggestion

El producto final de las diversas prácticas previamente mencionadas traen como resultado una arquitectura distinta, en contraste al no aplicar este enfoque centrado en reproducibilidad.
No adoptar estas prácticas y herramientas puede tener consecuencias negativas en el desarrollo de modelos en ciencia de datos.
La falta de reproducibilidad, la introducción de errores, la dificultad para colaborar en equipo y la lentitud en el proceso de desarrollo son obstáculos.
Sin embargo, hay que tener en cuenta que estas técnicas pueden requerir más tiempo y esfuerzo al principio del proceso de desarrollo.


Para lograr la reproducibilidad, hemos establecido un flujo de trabajo que incluye la definición de un ambiente virtualizado con las dependencias necesarias para ejecutarlo.
La implementación de resultados en un informe, la documentación detallada de los pasos y la separación clara entre código-datos mejoran el entendimiento del producto final.
El uso de _unit testing_ y _test driving development_ nos ha permitido garantizar que nuestro código funcione correctamente y cumpla con los requisitos del equipo.
A través de la implementación de pruebas, podemos detectar errores de manera temprana y asegurarnos de que cualquier cambio no cause efectos secundarios no deseados.
En cuanto a la colaboración, hemos adoptado la técnica de _PPP_, en la que dos desarrolladores trabajan juntos en el mismo proyecto.
Lo anterior fomenta la comunicación constante entre el equipo y mejorando la comprensión del modelo.
Estas técnicas nos conducen hacia un mejor entendimiento de nuestros datos.
Indiscutiblemente, estos resultados sopesan las dificultades para implementar estás técnicas.
```

2023-06-07 16:34 UTC, siduartep commented
Listo ! Ya se integraron todas las observaciones, gracias 😁

2023-06-21 16:15 UTC, nepito approved these changes
Excelente @siduartep voy a cerrar el _pr_. Muchas gracias por atender los comentarios.

2023-06-21 16:17 UTC, merged