Agrega entrada sobre herramientas para la comunicación
IslasGECI/islasgeci.github.io pull request #46
Opened 2020-09-04 19:28 UTC by evaristor

2020-12-16 20:24 UTC, MaritzaB requested changes
Hola Evaristo. Te dejo mi revisión ✌🏽 😄 .

2020-12-16 20:24 UTC, MaritzaB commented on _posts/2020-08-08-comunicacion.md
> +  hacia afura de la dirección llevan copia para Evaristo; las comunicaciones hacia afura de la
En esta parte creo que lo que siempre hacemos es poner copia a ciencia.datos@islas.org.mx para que todo el equipo esté al tanto de la situación. Tal vez podríamos poner que llevan copia a Evaristo y a ciencia.datos@islas.org.mx 🤔 
```suggestion
  hacia afuera de la dirección llevan copia para Evaristo y ciencia.datos@islas.org.mx ; las comunicaciones hacia afuera de la
```

2020-12-16 20:24 UTC, MaritzaB commented on _posts/2020-08-08-comunicacion.md
> +  Discussions_, _Issues_ y _Trello_.
¿Y sí ponemos el stack overflow?
```suggestion
  Discussions_, _Issues_, _stack overflow_ y _Trello_.
```

2020-12-16 20:24 UTC, MaritzaB commented on _posts/2020-08-08-comunicacion.md
> +- **Videoconferencia**: Nos reunimos virtualmente mediante videoconferencias usando _Google Meet_.
¿Será prudente agregar el _whats app_? Ese lo utilizamos sólo para comunicarnos hacía afuera de la dirección si la persona con la que nos queremos comunicar se encuentra en campo 🤷🏽 .

2020-12-16 20:25 UTC, evaristor commented
Muchas gracias @MaritzaB por tu amable revisión.

2020-12-16 20:26 UTC, evaristor commented on _posts/2020-08-08-comunicacion.md
> +  Discussions_, _Issues_ y _Trello_.
Este ya no lo usamos por su costo.

2020-12-16 23:45 UTC, evaristor commented on _posts/2020-08-08-comunicacion.md
> +  hacia afura de la dirección llevan copia para Evaristo; las comunicaciones hacia afura de la
Tienez razón, y ciencia.datos@islas.org.mx ya incluye a Evaristo.

2020-12-16 23:46 UTC, evaristor commented on _posts/2020-08-08-comunicacion.md
> +- **Videoconferencia**: Nos reunimos virtualmente mediante videoconferencias usando _Google Meet_.
Sí, lo gragaré. Gracias por recordarlo.

2020-12-17 17:08 UTC, islasfernando approved these changes
van los correos en monoespaciado? si no ya está.

2020-12-17 17:09 UTC, nepito requested changes
Listo @evaristor

2020-12-17 17:09 UTC, nepito commented on _posts/2020-12-16-comunicacion.md
> +  encuentra en junta o en tomate. Chateamos mediante _Slack_. Para comunicamos con el personal que
Error de dedo
```suggestion
  encuentra en junta o en tomate. Chateamos mediante _Slack_. Para comunicarnos con el personal que
```

2020-12-17 17:09 UTC, nepito commented on _posts/2020-12-16-comunicacion.md
> +  respuesta el siguiente día hábil. Enviamos correos electrónicos mediante _Gmail_.
Creo que así como está escrito hablas de lo que en CD esperamos de los demás. Pero tal vez estés platicando de lo que esperamos (o esperas) de nosotros. Si es así, tal vez podrías cambiarlo a la siguiente manera:  
```suggestion
  tiempo de respuesta sea de un día hábil. Enviamos correos electrónicos mediante _Gmail_.
```

2020-12-17 17:09 UTC, nepito commented on _posts/2020-12-16-comunicacion.md
> +  forma de documentación sobre temas que estamos desarrollando gradualmente. Usuamos _GitHub
Error de dedo
```suggestion
  forma de documentación sobre temas que estamos desarrollando gradualmente. Usamos _GitHub
```

2020-12-17 17:09 UTC, MaritzaB requested changes
Listo, solo un error de dedo ✏️  y _i'm ok_

2020-12-17 17:09 UTC, MaritzaB commented on _posts/2020-12-16-comunicacion.md
> +  encuentra en junta o en tomate. Chateamos mediante _Slack_. Para comunicamos con el personal que
```suggestion
  encuentra en junta o en tomate. Chateamos mediante _Slack_. Para comunicarnos con el personal que
```

2020-12-17 17:29 UTC, evaristor commented
Muchas gracias @islasfernando @nepito y @MaritzaB por su revisión.

2020-12-17 17:32 UTC, MaritzaB approved these changes
Súper bien! 🙌🏽

2020-12-17 17:32 UTC, merged

2020-12-17 19:04 UTC, xwalls commented
@evaristor 
las cabeceras de la tabla, tienen ese formato o pueden modificarse?
si se pudiera podrían estar en español ✌

2020-12-17 19:10 UTC, evaristor commented
> las cabeceras de la tabla, tienen ese formato o pueden modificarse?
> si se pudiera podrían estar en español

Esas son etiquetas predefinadas de [Jekyll](https://jekyllrb.com/)