Agrega entrada sobre diferencia entre Ciencia de Datos y Análisis de Datos
IslasGECI/islasgeci.github.io pull request #47
Opened 2020-09-04 19:34 UTC by evaristor

2020-10-08 17:39 UTC, nepito requested changes
Aquí te dejo mi revisión. Esta es la manera que encontramos de activar al tarjeta

2020-10-08 17:39 UTC, nepito commented on _posts/2020-09-04-diferencia.md
> +En ocasiones, los términos Ciencia de Datos y Análisis de Datos se usan de manera intercambiable.
Por favor cambia a voz activa, aunque sea una pequeña mentira:
```suggestion
En ocasiones, usamos los términos Ciencia de Datos y Análisis de Datos de manera intercambiable.
```

2020-10-08 17:39 UTC, nepito commented on _posts/2020-09-04-diferencia.md
> +coexisten muchas definiciones. En esta nota no proveeré más definiciones sino que diferenciaré los
No me gusta como suena "actualmente" y "recientemente" en un solo enunciado. Creo que se escucha mejo alguna de las dos:
```suggestion
Ciencia de Datos es un concepto que ha ganado popularidad por lo que actualmente
coexisten muchas definiciones. En esta nota no proveeré más definiciones sino que diferenciaré los
```
otra posiblidad (no sé cómo funcionará esto de las dos sugerencias):
```suggestion
Ciencia de Datos es un concepto que recientemente ha ganado popularidad por lo que 
coexisten muchas definiciones. En esta nota no proveeré más definiciones sino que diferenciaré los
```

2020-10-08 17:39 UTC, nepito commented on _posts/2020-09-04-diferencia.md
> +determinar las propiedades de los datos y así elegir la técnica de análisis más apropiada. En
La palabra datos aparecerá por todas partes, así que creo que no estaría mal si en algunas ocasiones la podemos evitar:
```suggestion
determinar sus propiedades y así elegir la técnica de análisis más apropiada. En
```

2020-10-08 17:39 UTC, nepito commented on _posts/2020-09-04-diferencia.md
> +oceanólogos. La oceanología es una profesión generalistas que requiere con conocimientos sobre
Algo me suena raro aquí, creo que es un "con" de más:
```suggestion
oceanólogos. La oceanología es una profesión generalista que requiere conocimientos sobre
```
Además había un problema de concordancia

2020-10-08 17:39 UTC, nepito commented on _posts/2020-09-04-diferencia.md
> +mientras que el Anális de Datos valora el resultado por encima que el código. Abusando de la
Error de dedo:
```suggestion
mientras que el Análisis de Datos valora el resultado por encima que el código. Abusando de la
```

2020-10-08 18:57 UTC, evaristor commented
Muchas gracias por tan amable revisión

2020-10-08 19:00 UTC, evaristor commented on _posts/2020-09-04-diferencia.md
> +coexisten muchas definiciones. En esta nota no proveeré más definiciones sino que diferenciaré los
Sí funcionó bien eso de incluir dos sugerencias. Cuando acepté una la otra ya no estaba disponible.

2020-10-15 23:02 UTC, MaritzaB requested changes
Holi @evaristor creo que va por buen camino el post. Te dejo unos cuantos comentarios, y más adelante le daré otra revisión para poder aportar mi granito de arena :ok_hand:.

2020-10-22 22:45 UTC, islasfernando requested changes
Dejo algunos comentarios

2020-10-22 22:45 UTC, islasfernando commented on _posts/2020-09-04-diferencia.md
> +GECI creamos el equipo de Análisis de Datos. En este equipo usábamos las técnicas de procesamiento y análisis de datos comúnmente practicadas en las ciencias naturales por los investigadores o
```suggestion
Ciencia de Datos y Análisis de Datos basándome en la historia de nuestro equipo en GECI. En 2014, creamos el equipo de Análisis de Datos en GECI. En este equipo usábamos las técnicas de procesamiento y análisis de datos comúnmente practicadas en las ciencias naturales por los investigadores o
```

2020-10-22 22:45 UTC, islasfernando commented on _posts/2020-09-04-diferencia.md
> +que una ecóloga y ecología más que una programadora.
Supongo que falta agregar algo?

2020-10-22 22:45 UTC, islasfernando commented on _posts/2020-09-04-diferencia.md
> +Científica de Datos.
No me convence esta oración..

2020-10-23 19:08 UTC, evaristor commented
Gracias @islasfernando. Atiendo tu comentarios.

2020-10-23 20:31 UTC, evaristor commented on _posts/2020-09-04-diferencia.md
> +GECI creamos el equipo de Análisis de Datos. En este equipo usábamos las técnicas de procesamiento y análisis de datos comúnmente practicadas en las ciencias naturales por los investigadores o
Listo

2020-10-23 20:31 UTC, evaristor commented on _posts/2020-09-04-diferencia.md
> +que una ecóloga y ecología más que una programadora.
Sí, todavía no está terminado.

2020-11-03 20:45 UTC, islasfernando requested changes

2020-11-03 20:45 UTC, islasfernando commented on _posts/2020-10-27-diferencia.md
> +regresión logística y k-medias.
```suggestion
1\. En Ciencia de Datos usamos modelos matemáticos predictivos, mientras que en Análisis de Datos usábamos únicamente estadística descriptiva.
Seguimos utilizando la estadística descriptiva en el análisis exploratorio de datos (AED) para
determinar las propiedades de los datos y así elegir la técnica de análisis más apropiada. En
ocasiones, el AED es suficiente para contestar la pregunta planteada. Pero actualmente también
usamos técnicas analíticas con mayor costo computacional como de _machine learning_ (aprendizaje
automatizado), estadística bayesiana, bootstraping,
regresión logística y k-medias.
```

2020-11-03 20:45 UTC, islasfernando commented on _posts/2020-10-27-diferencia.md
> +regresión logística y k-medias.
Otra opción es agregar los métodos explícitamente al inicio.

```suggestion
1\. En Ciencia de Datos usamos modelos predictivos como _machine learning_ (aprendizaje
automatizado), estadística bayesiana, bootstraping, regresión logística y k-medias.
Antes, en Análisis de Datos usábamos únicamente estadística descriptiva.
Seguimos utilizando la estadística descriptiva en el análisis exploratorio de datos (AED) para
determinar las propiedades de los datos y así elegir la técnica de análisis más apropiada. En
ocasiones, el AED es suficiente para contestar la pregunta planteada. 
```

2020-11-03 20:45 UTC, islasfernando commented on _posts/2020-10-27-diferencia.md
> +2\. La Ciencia de Datos es una actividad que realizamos en equipo, mientras que el Análisis de Datos
```suggestion
2\. La Ciencia de Datos es una actividad interdisciplinaria que realizamos en equipo, mientras que el Análisis de Datos
```

2020-11-03 20:45 UTC, islasfernando commented on _posts/2020-10-27-diferencia.md
> +permite tratar los análisis con la misma mentalidad y herramientas que se acostrumbra usar para
Hay que reacomodar palabras para mejorar legibilidad, tal vez..
```suggestion
permite tratar los análisis y las herramientas con la misma mentalidad que se acostrumbra usar para
```

2020-11-10 20:30 UTC, MaritzaB requested changes
Hola @evaristor, que interesante es leer la historía del equipo, aparte de ser algo motivador de hacía dónde vamos como equipo. Te dejo algunas sugerencias. Tómalas con reserva y si con ellas consideras que podemos mejorar la nota, por favor incorporalas 😉.

2020-11-10 20:30 UTC, MaritzaB commented on _posts/2020-11-04-diferencia.md
> +planteada. Pero actualmente también usamos técnicas analíticas con mayor costo computacional como de
En esta parte me gustaría ver la razón por la cual tuvimos la necesidad de movernos de sólo hacer estadística descriptiva a implementar técnicas de mayor costo computacional _machine learning_, estadística bayesiana, etc.
Toma mi sugerencia con reserva, jeje. Los objetivos del AED los tomé de [Wikipedia](https://en.wikipedia.org/wiki/Exploratory_data_analysis#Development) así que seguramente hay una mejor descripción de esta parte 😄 
Y en la parte dónde hablas de las técnicas de mayor costo computacional, talvez podríamos contarles la necesidad que tuvimos para implementarlas 🤔. Ahí puse una sugerencia solamente para ver como se ve jeje.
```suggestion
técnica de análisis más apropiada. El AED es suficiente para sugerir hipótesis sobre las causas de los fenómenos observados, evaluar los supuestos en los que se basará la inferencia estadística o apoyar la selección de herramientas y técnicas estadísticas adecuadas. Sin embargo, cuando necesitamos contestar preguntas más allá de lo que estamos observando en los datos, utilizamos técnicas analíticas con mayor costo computacional como
```

2020-11-10 20:30 UTC, MaritzaB commented on _posts/2020-11-04-diferencia.md
> +analíticas.
```suggestion
de análisis de datos. Este cambio de enfoque nos permite aprovechar tanto las fortalezas del equipo cómo las
del resto de la organización. Mientras el resto de la organización nos asesora como expertos en
ecología, en el equipo de Ciencia de Datos nos especializamos en dominio de las técnicas
analíticas.
```

2020-11-17 20:44 UTC, evaristor commented on _posts/2020-11-04-diferencia.md
> +prácticas, las cuales adoptamos de las ciencias computacionales.
Muchas gracias por esta sugerencia. Este párrafo quedó mucho mejor con esta nueva estructura.

2020-11-19 22:00 UTC, nepito requested changes
Aquí te dejo mis comentarios @evaristor

2020-11-24 23:57 UTC, nepito requested changes
_Nice_  :heart_eyes: quedó a todo dar. Creo que el discurso es el mismo que del _facebook live_ :raised_hands: 

Aquí te dejo mis observaciones @evaristor

2020-11-24 23:57 UTC, nepito commented on _posts/2020-11-19-diferencia.md
> +Ciencia de Datos es un concepto que recientemente ha ganado popularidad por lo que actualmente
Acaba de aparecer _recientemente_ por lo que _actualmente_ no me gusta como suena. Qué te parace si lo cambiamos por _actualidad_:
```suggestion
Ciencia de Datos es un concepto que recientemente ha ganado popularidad por lo que en la actualidad
```

2020-11-24 23:57 UTC, nepito commented on _posts/2020-11-19-diferencia.md
> +por los investigadores o técnicos que trabajan en universidades o centros de investigación. En 2018,
Este enunciado está levemente largo (33 palabras) pero hay algo en él que no me gusta, pero no sé qué es. Te propongo que lo dividamos en dos para ver cómo se siente. Mi propuesta es:
```suggestion
GECI, creamos el equipo de Análisis de Datos en 2014. En este equipo usábamos las técnicas de procesamiento de datos y producción de resultados comúnmente practicadas en las ciencias naturales. Por nuestra formación, nosotros aprendimos esas técnicas de investigadores o técnicos que trabajan en universidades o centros de investigación. En 2018,
```

2020-11-24 23:57 UTC, nepito commented on _posts/2020-11-19-diferencia.md
> +causas de los fenómenos observados, evaluar las supocisiones en las que basaremos la inferencia
Error de dedo en [_suposiciones_](https://dle.rae.es/suposici%C3%B3n?m=form) es ese ce y no ce ese:
```suggestion
causas de los fenómenos observados, evaluar las suposiciones en las que basaremos la inferencia
```

2020-11-24 23:57 UTC, nepito commented on _posts/2020-11-19-diferencia.md
> +código"_](https://hackernoon.com/everything-as-code-explained-0ibg32a3), podríamos decir que en
¿Qué te parece en presente en lugar de condicional simple? :thinking: Creo que se lee más fácil:
```suggestion
código"_](https://hackernoon.com/everything-as-code-explained-0ibg32a3), podemos decir que en
```

2020-12-01 17:18 UTC, nepito requested changes
@evaristor hay nuevos archivos en este _pr_. ¿También los reviso?

2020-12-01 17:18 UTC, nepito commented on protocolo_basico/standard_name.md
> +Los posibles valores para el metadato `standard_name` se encuentran en [CF standard name
Me parece que es voz pasiva pero no estoy seguro. Qué te parece la siguiente sugerencia:
```suggestion
Algunos ejemplos para los valores del metadato `standard_name` los podemos encuentrar en [CF standard name
```

2020-12-01 17:58 UTC, evaristor commented
> @evaristor hay nuevos archivos en este _pr_. ¿También los reviso?

@nepito: Parece que cometí un error. No debería haber nuevos archivos. No los revises; corregiré mi error.

2020-12-01 18:03 UTC, evaristor commented
> @evaristor hay nuevos archivos en este _pr_. ¿También los reviso?

@nepito: Parece que es un error relacionado con el problema de que GitHub no actualiza la base del PR cuando la base cambia. ¿Recuerdas ese problema?
En realidad esos archivos ya se encuentran en la `develop` pero como la base no se actualiza este PR muestra como si los fueramos a agregar.

2020-12-01 18:05 UTC, evaristor commented
Parece que este truco lo resolvió en esta ocasión:
![image](https://user-images.githubusercontent.com/3461018/100779054-a7fa5080-33bc-11eb-9c65-43c26a88a980.png)

2020-12-01 18:06 UTC, evaristor commented
Definitivamente es un 🐞:

![image](https://user-images.githubusercontent.com/3461018/100779127-c6604c00-33bc-11eb-8c4c-2c95d0147001.png)

2020-12-01 18:47 UTC, nepito approved these changes
Ya quedó @evaristor. ¡Felicidades! :raised_hands:

2020-12-01 18:47 UTC, nepito commented on _posts/2020-11-30-diferencia.md
> +permite tratar los análisis con la misma mentalidad que los desarroladores de software acostumbran
Tenái dudas de si llevaba o no la preposición **a**, pero el ejemplo número 12 sugiere que no:
> 12. tr. Tecnol. Someter una sustancia o material a un proceso para purificarlo, analizarlo o darle otras propiedades. *Tratar los aceros.*

2020-12-01 18:48 UTC, merged