Revisión mensual ordinaria
IslasGECI/islasgeci.github.io pull request #54
Opened 2020-12-17 18:23 UTC by evaristor

2020-12-17 19:18 UTC, xwalls commented on _posts/2020-11-30-diferencia.md
> +área de especilidad. Actualmente contamos con 5 roles diferenciados: Curadora de datos, Analista de
un pequeño 🐛

2020-12-17 19:19 UTC, xwalls commented on _posts/2020-11-30-diferencia.md
> +área de especilidad. Actualmente contamos con 5 roles diferenciados: Curadora de datos, Analista de
especilidad == especialidad

2020-12-17 19:20 UTC, xwalls commented on _posts/2020-11-30-diferencia.md
> +permite tratar los análisis con la misma mentalidad que los desarroladores de software acostumbran
```suggestion
permite tratar los análisis con la misma mentalidad que los desarrolladores de software acostumbran
```

2020-12-17 19:21 UTC, xwalls commented on _posts/2020-11-30-diferencia.md
> +área de especilidad. Actualmente contamos con 5 roles diferenciados: Curadora de datos, Analista de
```suggestion
área de especialidad. Actualmente contamos con 5 roles diferenciados: Curadora de datos, Analista de
```

2020-12-17 19:25 UTC, xwalls commented on _posts/2020-12-16-comunicacion.md
> +- **Videoconferencia**: Nos reunimos virtualmente mediante videoconferencias usando _Google Meet_.
creo que se podría facilitar un poco más la lectura haciendo un salto de linea entre puntos:

```suggestion
- **Chat**: Este es el medio más rápido. Esperamos respuesta en minutos si la persona no se
  encuentra en junta o en tomate. Chateamos mediante _Slack_ con el personal que se encuentra en el
  continente y mediante _WhatsApp_ con el personal que se encuentra en el campo.
  
- **Correo electrónico**: Este es el medio oficial. Las comunicaciones que involucren entregas o
  solicitudes hacia afuera de la dirección las hacemos mediante correo electrónico. Las
  comunicaciones hacia afuera de la dirección llevan copia para todo el equipo y las comunicaciones
  hacia afuera de la organización llevan copia para el Director General. Esperamos que el tiempo de
  respuesta sea de un día hábil. Enviamos correos electrónicos mediante _Gmail_.
  
- **Foros**: Los foros los usamos para comunicaciones de larga duración. Los foros constituyen una
  forma de documentación sobre temas que estamos desarrollando gradualmente. Usamos _GitHub
  Discussions_, _Issues_ y _Trello_.
  
- **Videoconferencia**: Nos reunimos virtualmente mediante videoconferencias usando _Google Meet_.
```

2020-12-17 19:29 UTC, xwalls requested changes
antes de poder aprobar est PR te pido consideres los cambios anteriores

2021-01-14 18:10 UTC, MaritzaB commented
Qué ojo de águila 🦅 tienes @xwalls, estaban dificiles de detectar esos errores jaja. Ya quedaron resueltos 👌🏽.

2021-02-04 18:36 UTC, evaristor commented
Gracias @xwalls y @MaritzaB

2021-02-04 18:37 UTC, analislas approved these changes
@xwalls solicitó cambios y @MaritzaB los aceptó

2021-02-04 18:38 UTC, merged