✨ Add a new note for the blog
IslasGECI/islasgeci.github.io pull request #55
Opened 2021-01-28 23:54 UTC by nepito

2021-02-23 23:35 UTC, MaritzaB requested changes
Listo @nepito te dejé unos comentarios ✌🏽

2021-02-23 23:35 UTC, MaritzaB commented on _posts/2021-01-28-inspecciones.md
> +utilizamos en el trabajo diario del equipo. "_Peer Deskcheck_" es la manera estándar de definir las
Entiendo que estos posts son para nuestro propio uso, ¿Será muy redundante poner el equipo de Ciencia de Datos? 🤔
```suggestion
utilizamos en el trabajo diario del equipo de Ciencia de Datos. "_Peer Deskcheck_" es la manera estándar de definir las
```

2021-02-23 23:35 UTC, MaritzaB commented on _posts/2021-01-28-inspecciones.md
> +tienes. Los siguientes dos ejemplos son "_Peer Deskcheck_" y "_Pair Programing_", ambos los
En esta parte me quedó la sensación de que debía de estar esperando estos dos ejemplos. Yo pensé que nos ibamos a quedar con la revisión _Ad hoc_ 😅.
Creo que podríamos continuar el párrafo con algo como lo siguiente:
```suggestion
tienes. Otros ejemplos son "_Peer Deskcheck_" y "_Pair Programing_", ambos los
```

2021-02-23 23:35 UTC, MaritzaB commented on _posts/2021-01-28-inspecciones.md
> +debemos agregarles prioridad, estatus y tipo.
Creo que los bullets anterior y posterior a este tienen sangría y este no.

2021-02-23 23:35 UTC, MaritzaB commented on _posts/2021-01-28-inspecciones.md
> +  profesor dirigiéndose a sus estudiantes. La tiempo estimado de la reunión de inspección es de 200
```suggestion
  La descripción que haga el lector durante la reunión deberá ser como la de un o una profesora dirigiéndose a sus estudiantes. La tiempo estimado de la reunión de inspección es de 200
```

2021-02-23 23:35 UTC, MaritzaB commented on _posts/2021-01-28-inspecciones.md
> +otros inspectores hagan.
Que te parece que nombremos los roles y después los describamos de la siguiente manera:

```suggestion
- Autor o autora.  No tiene permitido moderar, leer o contar, ya que el está muy cerca al trabajo 
como para ser objetivo. Además, esto podrá ayudarle a prestar más atención a los comentarios que los
otros inspectores hagan. 
```
No vi abajo a alguien designado para _contar_, ¿ese es otro rol?

2021-02-23 23:35 UTC, MaritzaB commented on _posts/2021-01-28-inspecciones.md
> +- El lector será quien presenta pedazos de código. La idea es probar la claridad del código. La
```suggestion
- Lector o lectora. Será quien presenta pedazos de código. La idea es probar la claridad del código. La
```

2021-02-23 23:35 UTC, MaritzaB commented on _posts/2021-01-28-inspecciones.md
> +- El moderador debe de mandar las noticias el aviso de la reunión con los eventos, las fechas, los
```suggestion
- Moderador o moderadora. Debera de mandar las noticias el aviso de la reunión con los eventos, las fechas y los
```

2021-02-23 23:35 UTC, MaritzaB commented on _posts/2021-01-28-inspecciones.md
> +tiempos. Si el autor y el moderador asignan alguna respnsabilidad para los inspectores, el moderador
```suggestion
tiempos. Si el autor y el moderador asignan alguna responsabilidad para los inspectores, el moderador
```

2021-02-23 23:35 UTC, MaritzaB commented on _posts/2021-01-28-inspecciones.md
> +- Los inspectores. Al resto de los participantes los llamamos inspecoes. Ellos revisarán el código
```suggestion
- Las y los inspectores. Al resto de los participantes los llamamos inspectores. Ellos revisarán el código
```

2021-02-23 23:35 UTC, MaritzaB commented on _posts/2021-01-28-inspecciones.md
> +La inspección consiste en un par de reuniones y los participantes de la inspección cumplan con
```suggestion
La inspección consiste en un par de reuniones donde las y los participantes de la inspección cumplen con
```

2021-02-23 23:35 UTC, MaritzaB commented on _posts/2021-01-28-inspecciones.md
> +diferentes roles en las reuniones. El objetivo principal de la inspección deberá ser encontrar
```suggestion
diferentes roles. El objetivo principal de la inspección deberá ser encontrar
```

2021-02-23 23:35 UTC, MaritzaB commented on _posts/2021-01-28-inspecciones.md
> +## ¿Quiénes son los participantes y cuáles sus roles?
Más abajo especificas que es para la reunión de inspección, ¿qué te parece si lo especificamos desde el título?
```suggestion
## ¿Quiénes son los participantes y cuáles sus roles en una reunión de inspección?
```

2021-02-23 23:35 UTC, MaritzaB commented on _posts/2021-01-28-inspecciones.md
> +  intervención que hará cada inspector en la reunión de inspección será decir algo positivo del
```suggestion
  intervención que hará cada inspector en la reunión será decir algo positivo del
```

2021-02-23 23:35 UTC, MaritzaB commented on _posts/2021-01-28-inspecciones.md
> +  inspectores tienen la información necesaria para entender el código. Así si en la revisión ellos
```suggestion
- La revisión general. Esta es un reunión la cual dirige el o la autora. El fin es juzgar si las o los
  inspectores tienen la información necesaria para entender el código. Así si en la revisión ellos
```

2021-02-23 23:35 UTC, MaritzaB commented on _posts/2021-01-28-inspecciones.md
> +  La descripción que haga el lector durante la reunión deberá ser como la de una profesora o
```suggestion
  La descripción que haga la o el lector durante la reunión deberá ser como la de una profesora o
```

2021-02-23 23:55 UTC, xwalls reviewed
No quedó mucho tras la revisión de maritza pero algo es algo ✏️

2021-02-23 23:55 UTC, xwalls commented on _posts/2021-01-28-inspecciones.md
> +- El seguimiento. En esta parte el moderador u otra persona asignada se reune con el autor para
detalle minúsculo ;)
```suggestion
- El seguimiento. En esta parte el moderador u otra persona asignada se reúne con el autor para
```

2021-02-24 19:12 UTC, nepito commented on _posts/2021-01-28-inspecciones.md
> +otros inspectores hagan.
Aun no estoy seguro de ese rol. Creo que lo pondré y después vemos si vale la pena o no

2021-02-24 23:58 UTC, nepito reviewed
@MaritzaB y @xwalls ya atendí la mayoría de sus comentarios. Le pasé la bolita a @islasfernando y después les pediré la revisión buena. 

La idea es que vayamos viendo de qué se va a tratar la inspección del viernes 5 de marzo.

2021-02-24 23:58 UTC, nepito commented on _posts/2021-01-28-inspecciones.md
> +tienes. Los siguientes dos ejemplos son "_Peer Deskcheck_" y "_Pair Programing_", ambos los
No estoy seguro de a qué te refieres con "me quedó la sensación de que debía de estar esperando estos dos ejemplos", pues esos son los ejemplo los "explico" en la siguiente oración :thinking:

2021-02-25 17:16 UTC, islasfernando requested changes
Por ahora marque solo cuestiones de estilo :v:

2021-02-25 19:28 UTC, nepito commented on _posts/2021-01-28-inspecciones.md
> +  final de la revisión los inspectores deberán tener el paquete de inspección y los objetivos del
No. Con paquete me refiero a las herramientas (guías de estilo), código (los archivos que revisaremos) y las reglas (cuáles serás los roles).

2021-02-25 22:59 UTC, evaristor requested changes
Aquí va una tanda

2021-02-25 22:59 UTC, evaristor commented on _posts/2021-01-28-inspecciones.md
> +- **Autor o autora**: No tiene permitido moderar, leer o contar, ya que el está muy cerca al trabajo
¿Falta un acento?
```suggestion
- **Autor o autora**: No tiene permitido moderar, leer o contar, ya que él está muy cerca al trabajo
```

2021-02-25 22:59 UTC, evaristor commented on _posts/2021-01-28-inspecciones.md
> +- **Autor o autora**: No tiene permitido moderar, leer o contar, ya que el está muy cerca al trabajo
¿Es lenguaje inclusivo?
```suggestion
- **Autor o autora**: No tiene permitido moderar, leer o contar, ya que él o ella está muy cerca al trabajo
```

```suggestion
- **Autor o autora**: No tiene permitido moderar, leer o contar, ya que está muy cerca al trabajo
```

2021-02-25 22:59 UTC, evaristor commented on _posts/2021-01-28-inspecciones.md
> +  como para ser objetivo. Además, esto podrá ayudarle a prestar más atención a los comentarios que
¿Falta inclusión?
```suggestion
  como para actuar con objetividad. Además, esto podrá ayudarle a prestar más atención a los comentarios que
```

2021-02-25 22:59 UTC, evaristor commented on _posts/2021-01-28-inspecciones.md
> +  los otros inspectores hagan.
```suggestion
  las y los otros inspectores hagan. 
```

2021-02-25 22:59 UTC, evaristor commented on _posts/2021-01-28-inspecciones.md
> +  las fechas y los tiempos. Si el autor y el moderador asignan alguna responsabilidad para los
```suggestion
  las fechas y los tiempos. Si el o la autora y el o la moderadora asignan alguna responsabilidad para las y los
```

2021-02-25 22:59 UTC, evaristor commented on _posts/2021-01-28-inspecciones.md
> +  inspectores, el moderador deberá de comunicar esa información junto con las listas de revisión
```suggestion
  inspectores, el o la moderadora deberá de comunicar esa información junto con las listas de revisión
```

2021-02-25 22:59 UTC, evaristor commented on _posts/2021-01-28-inspecciones.md
> +- **Las y los inspectores**: Al resto de los participantes los llamamos inspectores. Ellos revisarán
```suggestion
- **Las y los inspectores**: Al resto de las y los participantes los llamamos inspectores. Ellas y ellos revisarán
```

2021-02-25 22:59 UTC, evaristor commented on _posts/2021-01-28-inspecciones.md
> +  examinan el código en busca de posibles errores, usando los _check list_ de defectos. Escriben las
```suggestion
  examinan el código en busca de posibles errores, usando los _checklist_ de defectos. Escriben las
```

2021-02-25 22:59 UTC, evaristor commented on _posts/2021-01-28-inspecciones.md
> +  líneas de código por hora. El tiempo de preparación debería de ser similar al tiempo que tomará la
```suggestion
  La descripción que haga el lector durante la reunión deberá ser como la de un o una profesora dirigiéndose a sus estudiantes. El tiempo estimado de la reunión de inspección es de una hora por cada 200
  líneas de código. El tiempo de preparación debería de ser similar al tiempo que tomará la
```

2021-02-25 22:59 UTC, evaristor commented on _posts/2021-01-28-inspecciones.md
> +  inspección, es decir 200 líneas por hora.
```suggestion
  inspección, es decir una hora por cada 200 líneas.
```

2021-02-25 22:59 UTC, evaristor commented on _posts/2021-01-28-inspecciones.md
> +- **El seguimiento**: En esta parte el moderador u otra persona asignada se reúne con el autor para
```suggestion
- **El seguimiento**: En esta parte el o la moderadora u otra persona asignada se reúne con el o la autora para
```

2021-02-25 22:59 UTC, evaristor commented on _posts/2021-01-28-inspecciones.md
> +  errores. Si ayudó a que el equipo mejorara la calidad en el desarrollo y en la revisión de código.
Parece que esta es una oración incompleta:
"Si ayudó a que el equipo mejorara la calidad en el desarrollo y en la revisión de código."

2021-02-26 23:34 UTC, marthapaolajm requested changes

2021-02-26 23:34 UTC, marthapaolajm commented on _posts/2021-01-28-inspecciones.md
> +  ellos detectan un _bug_ deberán esperan hasta la reunión de inspección para señalarlo. A más
```suggestion
  ellos detectan un _bug_ deberán esperar hasta la reunión de inspección para señalarlo. A más
```

2021-04-08 19:18 UTC, evaristor requested changes

2021-04-08 19:18 UTC, evaristor commented on _posts/2021-01-28-inspecciones.md
> +## ¿Quiénes son los participantes y cuáles sus roles en una inspección?
```suggestion
## ¿Quiénes participan y cuáles sus roles en una inspección?
```

```suggestion
## ¿Quiénes son las y los participantes y cuáles sus roles en una inspección?
```

2021-04-08 21:42 UTC, evaristor approved these changes

2021-04-09 19:09 UTC, islasfernando approved these changes

2021-04-09 19:09 UTC, islasfernando commented on _posts/2021-01-28-inspecciones.md
> +pares son "_Walkthrough_", "_Team Review_" e "_Ispection_". Para Karl, la revisión más formal es la
Traducir "_Walkthrough_", "_Team Review_" e "_Ispection_" ?? 🤔

2021-04-12 18:50 UTC, closed without merging

2021-04-12 18:54 UTC, nepito commented on _posts/2021-01-28-inspecciones.md
> +pares son "_Walkthrough_", "_Team Review_" e "_Ispection_". Para Karl, la revisión más formal es la
Perdón @islasfernando como me salió aprobado ya no atendí esta petición. En un momento la atiendo.