✨🗒️ Agrega entrada describiendo qué es lo que debemos automatizar
IslasGECI/islasgeci.github.io pull request #61
Opened 2021-03-17 16:41 UTC by evaristor

- [ ] Cumple con nuestr [guía de estilo para la prosa](https://islasgeci.github.io/guia_de_estilo/prosa)

2021-03-17 18:18 UTC, MaritzaB requested changes
Hola @evaristor , se ve muy bien, te dejo mis comentarios 😺

2021-03-17 18:18 UTC, MaritzaB commented on _posts/2021-03-17-automatiza-todo.md
> +ejecutar `geci-tdp2xls`. Debemos automatizar el respaldo y restauración de las bases de datos.
Siento que a lo largo del texto hay bastantes _debemos_. Creo que una manera en la que podríamos mejorar el texto es escribiendo las tareas pendientes como _bullets_. Además, con esto podemos lograr clasificar los temas. Por ejemplo: _Automatización en la curación de datos_, _Automatización en desarrollo web_, etc...
La de curación de datos podría ser la siguiente:
```suggestion
En la curación de datos, debemos automatizar las siguientes tareas:

- _Mutation testing_ de los datos para evaluar los _constraints_ de los _data packages_. 
- Eliminar la parte manual requerida después de ejecutar `geci-tdp2xls`.
- El respaldo y restauración de las bases de datos.
```
¿Qué opinas, nos ayudará? 🤔

2021-03-17 19:00 UTC, evaristor commented on _posts/2021-03-17-automatiza-todo.md
> +ejecutar `geci-tdp2xls`. Debemos automatizar el respaldo y restauración de las bases de datos.
Se ve bien. Incorporaré la sugerencia

2021-04-08 19:38 UTC, evaristor commented
Preferí agregarlo como [asunto clase 1](https://github.com/orgs/IslasGECI/teams/clase-1/discussions/18) en lugar de entrada al blog.

2021-04-08 19:38 UTC, closed without merging