📝 actualiza los estandard names de las variables
IslasGECI/islasgeci.github.io pull request #62
Opened 2021-04-05 20:10 UTC by xwalls

2021-04-05 21:30 UTC, evaristor requested changes
😄

2021-04-05 21:30 UTC, evaristor commented on protocolo_basico/standard_name.md
> +`catches`                 | Catches         | Capturas             | Cantidad de individuos capturados en trampas
_Catches_ es usado para pesquerías. Creo que _captures_ es más adecuado.

```suggestion
`number_of_captures`                 | Catches         | Capturas             | Cantidad de individuos capturados en trampas
```

2021-04-05 21:30 UTC, evaristor commented on protocolo_basico/standard_name.md
> +**`standard_name`**       | **long_name**   | Nombre Largo         | Descripción
Está raro que pongamos "**long_name**" (snake_case) y "Nombre Largo" (con espacio y mayúsculas). Deberíamos uniformizar.

Opción 1:

```suggestion
`standard_name`       | `long_name`   |  `nombre_largo`         | Descripción
```

Opción 2:
```suggestion
Standard Name       | Long Name   | Nombre Largo         | Descripción
```

2021-04-05 21:30 UTC, evaristor commented on protocolo_basico/standard_name.md
> +`effort`                  | Effort          | Esfuerzo             | Cantidad de recursos necesarios por dia para lograr una labor, por ejemplo: capturar un individuo
Podría ser por hora o por año.

```suggestion
`effort`                  | Effort          | Esfuerzo             | Cantidad de recursos necesarios para lograr una labor, por ejemplo: capturar un individuo
```

2021-04-08 19:48 UTC, evaristor commented
@MaritzaB @xwalls ¿Cómo vamos?

2021-04-27 19:34 UTC, xwalls commented on protocolo_basico/standard_name.md
> +`catches`                 | Catches         | Capturas             | Cantidad de individuos capturados en trampas
muchas gracias evaristo! aceptamos tu sugerencia.

2021-04-27 19:35 UTC, xwalls commented on protocolo_basico/standard_name.md
> +**`standard_name`**       | **long_name**   | Nombre Largo         | Descripción
muchas gracias evaristo! nos parece más adecuada la segunda opción.

2021-04-27 19:38 UTC, xwalls commented on protocolo_basico/standard_name.md
> +`effort`                  | Effort          | Esfuerzo             | Cantidad de recursos necesarios por dia para lograr una labor, por ejemplo: capturar un individuo
muchas gracias evaristo!
decidimos aceptar tu sugerencia.

2021-04-27 20:17 UTC, evaristor requested changes
> En la siguiente tabla se muestran algunos de los nombres estándares más usados.

Creo que hay que cambiar eso a algo así como:

En la siguiente tabla se muestran los nombres estándares reconocidos por este protocolo.

---

> y agregarlos a `misctools/schemas/protocolo-geci.json`.

¿Es eso correcto?

2021-04-27 20:17 UTC, evaristor commented on protocolo_basico/standard_name.md
> +`number_of_captures`                 | Catches         | Capturas             | Cantidad de individuos capturados en trampas
```suggestion
`number_of_captures`                 | Captures         | Capturas             | Cantidad de individuos capturados en trampas
```

2021-04-27 22:50 UTC, MaritzaB commented
> y agregarlos a misctools/schemas/protocolo-geci.json.
> 
> ¿Es eso correcto

Qué buena observación @evaristor! 🤗  
A donde hay que agregarlos es al repo de `metadata_tools` en el archivo `_StandardName.py`, ya corregí la redacción 👌🏽 .

2021-04-27 23:05 UTC, evaristor requested changes

2021-04-27 23:05 UTC, evaristor commented on protocolo_basico/standard_name.md
>  _Tabla: Ejemplo de nombres estándares reconocidos por este protocolo._
```suggestion
_Tabla: Nombres estándares reconocidos por este protocolo._
```

2021-04-27 23:05 UTC, evaristor commented on protocolo_basico/standard_name.md
> +implementar algunos nombres estándar. En la siguiente tabla se muestran los nombres estándares
¿Cuál prefieres: _nombres estándares_ o _nombres estándar_?

```suggestion
implementar algunos nombres estándares. En la siguiente tabla se muestran los nombres estándares
```

```suggestion
implementar algunos nombres estándar. En la siguiente tabla se muestran los nombres estándar
```

2021-04-27 23:19 UTC, MaritzaB commented on protocolo_basico/standard_name.md
> +implementar algunos nombres estándar. En la siguiente tabla se muestran los nombres estándares
Mmm me gusta como suena el primero, pero siento que el segundo es el bueno 🤔 , deja le pregunto a google 🤪

2021-04-27 23:23 UTC, MaritzaB commented on protocolo_basico/standard_name.md
> +implementar algunos nombres estándar. En la siguiente tabla se muestran los nombres estándares
[Google dice lo siguiente](https://www.fundeu.es/recomendacion/medidas-estandar-estandares/#:~:text=El%20t%C3%A9rmino%20est%C3%A1ndar%20(adaptaci%C3%B3n%20del,%2C%20patr%C3%B3n%2C%20nivel').) con un ejemplo:

> Medidas estándar y medidas estándares son plurales apropiados de medida estándar.

> En el primer caso, cuando acompaña a un sustantivo en plural, lo adecuado es que adopte también la forma plural: medidas estándares, costes estándares, diseños estándares…
> 
> No obstante, también puede permanecer invariable si se interpreta que se está empleando como un sustantivo en aposición: medidas estándar, costes estándar, diseños estándar…

Así que si... es el que más nos guste jajaja

2021-04-28 14:04 UTC, evaristor requested changes

2021-04-28 14:04 UTC, evaristor commented on protocolo_basico/standard_name.md
>  Para incluir nuevos nombres estándares que no sean parte de la convención CF se debe utilizar la
```suggestion
Para incluir nuevos nombres estándar que no sean parte de la convención CF se debe utilizar la
```

2021-04-28 14:04 UTC, evaristor commented on protocolo_basico/standard_name.md
>  estándares_](http://cfconventions.org/Data/cf-standard-names/docs/guidelines.html) de la convención
```suggestion
estándar_](http://cfconventions.org/Data/cf-standard-names/docs/guidelines.html) de la convención
```

2021-04-28 14:04 UTC, evaristor commented on protocolo_basico/standard_name.md
> +_Tabla: Nombres estándares reconocidos por este protocolo._
```suggestion
_Tabla: Nombres estándar reconocidos por este protocolo._
```

2021-04-28 15:06 UTC, evaristor approved these changes
💯😆
![image](https://user-images.githubusercontent.com/3461018/116427182-a6f90e00-a7f8-11eb-8768-82445cd200e5.png)

2021-04-28 15:30 UTC, merged