Imitadores y espías
IslasGECI/islasgeci.github.io pull request #67
Opened 2021-05-03 22:16 UTC by nepito

2021-05-05 17:35 UTC, MaritzaB requested changes
Listo @nepito, se ve muy bien la nota.
Solo dejo algunos comentarios acerca de errores de dedo y algunas dudas 😉

2021-05-05 17:35 UTC, MaritzaB commented on _posts/2021-05-10-imitadores.md
> +En la sección referenicas está la lista de material en la que nos inspiramos para escribir esta
```suggestion
En la sección referencias está la lista de material en la que nos inspiramos para escribir esta
```

2021-05-05 17:35 UTC, MaritzaB commented on _posts/2021-05-10-imitadores.md
> +El objetivo es probar a la función `get_subset_morphometric_data`. Esta función tiene dos variables
Hola @nepito, aquí me queda una duda de qué es un imitador 🤔. ¿Podrías agregar una breve explicación de qué es o para que sirve un imitador, por favor 🙏?
Yo sé que tal vez eso se ve en el código más abajo, pero para tenerlo un poco más clara la idea 😅

2021-05-05 17:35 UTC, MaritzaB commented on _posts/2021-05-10-imitadores.md
> +Lo que queremos es probar `get_subset_morphometric_data`) y no desviarnos con la
```suggestion
Lo que queremos es probar `get_subset_morphometric_data` y no desviarnos con la
```

2021-05-05 17:35 UTC, MaritzaB commented on _posts/2021-05-10-imitadores.md
> +[Stargilr](https://thea.codes/) sugiere que no usemos este tipo de imitadores. El motivo es que si al
¿Será stargirl?

```suggestion
[Stargirl](https://thea.codes/) sugiere que no usemos este tipo de imitadores. El motivo es que si al
```

2021-05-05 17:35 UTC, MaritzaB commented on _posts/2021-05-10-imitadores.md
> +Para atender la sugerencia de Stargilr podemos heredar la interface de alguna clase. Con este cambio
Aquí también?
```suggestion
Para atender la sugerencia de Stargirl podemos heredar la interface de alguna clase. Con este cambio
```

2021-05-05 17:35 UTC, MaritzaB commented on _posts/2021-05-10-imitadores.md
> +ninguna de las funcionalidades de que tendría un objeto de la clase `Predictions_and_Parameters`,
```suggestion
ninguna de las funcionalidades que tendría un objeto de la clase `Predictions_and_Parameters`,
```

2021-05-05 17:35 UTC, MaritzaB commented on _posts/2021-05-10-imitadores.md
> +_chunk_ de código podemos notar que tenemos un imitador, tema que atendimos en los tres ejemplos
¿_chunk_ es lo mismo que bloque de código? 🤯

2021-05-05 17:35 UTC, MaritzaB commented on _posts/2021-05-10-imitadores.md
> +El método `savefig` de la clase `Plotter`. Y lo que nos interesa preguntarle al espía `makedirs` es
Creo que esta frase está incompleta, ¿no? 🤔
> El método `savefig` de la clase `Plotter`.

2021-05-05 17:35 UTC, xwalls requested changes
Es una entrada de blog muuy interesante y debo decir que tiene una calidad endemoniadamente buena. solo te dejo lo el unico detalle que fui capaz de encontrar.
Pero en general me encanto!

2021-05-05 17:35 UTC, xwalls commented on _posts/2021-05-10-imitadores.md
> +Lo que queremos es probar `get_subset_morphometric_data`) y no desviarnos con la
un pequeño paréntesis solitario de más ;)
```suggestion
Lo que queremos es probar `get_subset_morphometric_data` y no desviarnos con la
```

2021-05-05 17:38 UTC, evaristor requested changes
¡Excelente nota! ¿Planeas hacerle la competencia a Real Python?

2021-05-05 17:38 UTC, evaristor commented on _posts/2021-01-28-inspecciones.md
> +tags: equipo
Me parece que la categoría más apropiada es Programación.
```suggestion
tags: programacion
```

2021-05-05 17:38 UTC, evaristor commented on _posts/2021-05-10-imitadores.md
> +cómo los implementamos:
Corrige ancho de línea:

```suggestion
Lo que queremos es probar `get_subset_morphometric_data`) y no desviarnos con la implementación de
las clases a la que pertenecen `Cleaner_Morphometric` y `Predictor`. Sandi Metz propone en [este
video](https://youtu.be/v-2yFMzxqwU) utilizar imitadores. A continuación veremos cómo los
implementamos:
```

2021-05-05 17:38 UTC, evaristor commented on _posts/2021-05-10-imitadores.md
> +no fallará.
Corrige ancho de línea:

```suggestion
[Stargilr](https://thea.codes/) sugiere que no usemos este tipo de imitadores. El motivo es que si
al implementar las clases cambiamos las interfaces la prueba no se enterará del cambio y por lo
tanto no fallará.
```

2021-05-05 17:38 UTC, evaristor commented on _posts/2021-05-10-imitadores.md
> +podrás encontrar en `pollos_petrel/tests/tests_petrel_age_predictor.py`, en la consignación 66eb24.
¿Conviene agregar un enlace?:

```suggestion
podrás encontrar en [`pollos_petrel/tests/tests_petrel_age_predictor.py`, en la consignación 66eb24](https://bitbucket.org/IslasGECI/pollos_petrel/src/66eb24183f81df85350a715cc04ae120324a01df/tests/test_petrel_age_predictor.py).
```

2021-05-05 17:38 UTC, evaristor commented on _posts/2021-05-10-imitadores.md
> +El objetivo es probar a la función `get_subset_morphometric_data`. Esta función tiene dos variables
```suggestion
El objetivo es probar la función `get_subset_morphometric_data`. Esta función tiene dos variables
```

2021-05-05 17:38 UTC, evaristor commented on _posts/2021-05-10-imitadores.md
> +de entrada `Cleaner_Morphometric` y `Predictor`. Las dos variables dos objetos de clases que aun no
```suggestion
de entrada `Cleaner_Morphometric` y `Predictor`. Las dos variables son objetos de clases que aun no
```

2021-05-05 17:38 UTC, evaristor commented on _posts/2021-05-10-imitadores.md
> +Lo que queremos es probar `get_subset_morphometric_data`) y no desviarnos con la
¿Sobra un paréntesis?:

```suggestion
Lo que queremos es probar `get_subset_morphometric_data` y no desviarnos con la
```

2021-05-05 17:38 UTC, evaristor commented on _posts/2021-05-10-imitadores.md
> +la interfaz cambia la prueba nos recordará que debemos actualizarla. En el primer ejemplo generamos
No me queda totalmente claro esto:

> Con este cambio la interfaz cambia la prueba nos recordará que ...

No estoy seguro sobre como corregirlo.

2021-05-05 17:38 UTC, evaristor commented on _posts/2021-05-10-imitadores.md
> +En los últimos dos ejemplos, los objetos imitadores siguen una interfaz determinada. A `Parameters`
¿Es equivalente?

```suggestion
En los dos ejemplos anteriores, los objetos imitadores siguen una interfaz determinada. A `Parameters`
```

Lo pregunto por que por un nstante dudé si te referías a los ultimos dos ejemplos que vienen abajo, al final de la entrada, o los últimos dos ejemplos antes de esta línea. No estoy seguro a cuales dos ejemplos te refieres.

2021-05-05 17:38 UTC, evaristor commented on _posts/2021-05-10-imitadores.md
> +Habrá ocasiones en las que lo que nos interesa saber si hicimos llamados a funciones de terceros y
```suggestion
Habrá ocasiones en las que lo que nos interesa saber es si hicimos llamados a funciones de terceros y
```

```suggestion
Habrá ocasiones en las que lo que nos interesa es saber si hicimos llamados a funciones de terceros y
```

2021-05-05 17:38 UTC, evaristor commented on _posts/2021-05-10-imitadores.md
> +desarrolladores, a nosotros lo que nos podría interesar es saber si estamos haciendo el llamado de
> lo que nos podría interesar es saber si

Suena levemente repetitivo respecto a la primer oración del párrafo.

2021-05-05 17:38 UTC, evaristor commented on _posts/2021-05-10-imitadores.md
> +El método `savefig` de la clase `Plotter`. Y lo que nos interesa preguntarle al espía `makedirs` es
> El método `savefig` de la clase `Plotter`.

¿Es como un título o le hace falta un verbo?

2021-05-05 17:38 UTC, evaristor commented on _posts/2021-05-10-imitadores.md
> +espías. Los ejemplos son de cómo los usamos en la Dirección de Ciencias de Datos. Tratamos de seguir
```suggestion
espías. Los ejemplos son de cómo los usamos en la Dirección de Ciencias de Datos de GECI. Tratamos de seguir
```

2021-05-05 17:44 UTC, MaritzaB requested changes

2021-05-05 17:44 UTC, MaritzaB commented on _posts/2021-05-10-imitadores.md
> +espías. Los ejemplos son de cómo los usamos en la Dirección de Ciencias de Datos. Tratamos de seguir
```suggestion
espías. Los ejemplos son de cómo los usamos en la Dirección de Ciencia de Datos de GECI. Tratamos de seguir
```

2021-05-05 23:04 UTC, nepito commented on _posts/2021-01-28-inspecciones.md
> +tags: equipo
Excelente, ahí la pondré

2021-05-05 23:05 UTC, nepito commented on _posts/2021-05-10-imitadores.md
> +podrás encontrar en `pollos_petrel/tests/tests_petrel_age_predictor.py`, en la consignación 66eb24.
Claro que conviene, muchas gracias :raised_hands:

2021-05-05 23:05 UTC, nepito commented on _posts/2021-05-10-imitadores.md
> +En la sección referenicas está la lista de material en la que nos inspiramos para escribir esta
Muchas gracias @MaritzaB

2021-05-05 23:06 UTC, nepito commented on _posts/2021-05-10-imitadores.md
> +El objetivo es probar a la función `get_subset_morphometric_data`. Esta función tiene dos variables
Tienes toda la razón. Nunca lo digo solo lo estoy utilizando. Mañana atiendo esta petición :raised_hands:

2021-05-05 23:07 UTC, nepito commented on _posts/2021-05-10-imitadores.md
> +Lo que queremos es probar `get_subset_morphometric_data`) y no desviarnos con la
Sí, creo que me lo traje del _copy_ y _paste_ del archivo fuente. Muchas gracias :raised_hands:

2021-05-05 23:10 UTC, nepito commented on _posts/2021-05-10-imitadores.md
> +[Stargilr](https://thea.codes/) sugiere que no usemos este tipo de imitadores. El motivo es que si al
Tienes toda la razón, ella es la primera que inspiró esta entrada y así le pago :facepalm: . Muchas gracias @MaritzaB

2021-05-06 16:30 UTC, nepito commented on _posts/2021-05-10-imitadores.md
> +El objetivo es probar a la función `get_subset_morphometric_data`. Esta función tiene dos variables
@MaritzaB esto fue lo que agregué:
>Los imitadores son objetos que imitan el comportamiento de objetos reales en formas controladas. Así, creamos imitadores para probar el comportamiento de otro objeto, en la misma manera que los diseñadores de carros usan un maniquí de prueba de choque para simular la dinámica de un humano en una colisión de autos.

2021-05-06 16:49 UTC, MaritzaB commented on _posts/2021-05-10-imitadores.md
> +El objetivo es probar a la función `get_subset_morphometric_data`. Esta función tiene dos variables
woow @nepito, quedó más claro que el agua! 💧 jajaja. Muchas gracias por la explicación 🙌🏽

2021-05-06 16:51 UTC, nepito commented on _posts/2021-05-10-imitadores.md
> +El objetivo es probar a la función `get_subset_morphometric_data`. Esta función tiene dos variables
muchas gracias a ti @MaritzaB . Por la revisión :raised_hands:

2021-05-06 16:59 UTC, evaristor requested changes
¿Por favor podrías numerar los ejemplos? Una manera de hacerlo podría ser agregando un "encabezado" a cada bloque de código (como si fuera una tabla): Ejemplo 1: Imitador bla, bla, ...

2021-05-06 16:59 UTC, evaristor commented on _posts/2021-05-10-imitadores.md
> +En la sección referencias está la lista de material en la que nos inspiramos para escribir esta
```suggestion
En la sección Referencias está la lista de material en la que nos inspiramos para escribir esta
```
```suggestion
En la sección de referencias está la lista de material en la que nos inspiramos para escribir esta
```
```suggestion
En la sección de las referencias está la lista de material en la que nos inspiramos para escribir esta
```

2021-05-06 17:16 UTC, evaristor commented
Creo que hace falta hacer referencia a los bloques de código. Explicar más que es lo que debemos ver en cada bloque. Me tomó tiempo entender que algunos bloques son un acercamiento de los anteriores. No me quedaba claro que en el bloque de abajo estabas resaltando algo del bloque de arriba. Tal vez podríamos usar "encabezados" como en las tablas (Ejemplo 1: Imitador que bla, bla) y hacer  referencia al encabezado en la prosa. En el ejemplo 1 podemos ver que... En el ejemplo 2.1 contrasta que...
Otra opción es que agreguemos comentarios dentro de los bloques de código que nos facilite ver lo que quieres señalar. Tal vez se pueden implementar ambas?

2021-05-06 21:46 UTC, nepito commented on _posts/2021-05-10-imitadores.md
> +```
```suggestion
![image](https://user-images.githubusercontent.com/35377740/117369179-6a24bb00-ae79-11eb-9f7a-325728d2e360.png)
```

2021-05-06 22:12 UTC, nepito commented
> Creo que hace falta hacer referencia a los bloques de código. Explicar más que es lo que debemos ver en cada bloque. Me tomó tiempo entender que algunos bloques son un acercamiento de los anteriores. No me quedaba claro que en el bloque de abajo estabas resaltando algo del bloque de arriba. Tal vez podríamos usar "encabezados" como en las tablas (Ejemplo 1: Imitador que bla, bla) y hacer referencia al encabezado en la prosa. En el ejemplo 1 podemos ver que... En el ejemplo 2.1 contrasta que...
> Otra opción es que agreguemos comentarios dentro de los bloques de código que nos facilite ver lo que quieres señalar. Tal vez se pueden implementar ambas?

@evaristor serías tan amable de pegarle otra leída por favor. Creo que el ejemplo más complicado es el del parche a un método. Fue a ese ejemplo al que traté de mejorar. En el vs-code podemos renderizar la imagen.

2021-05-07 00:13 UTC, nepito commented
Listo @evaristor ya subrayé el código y lo describí.

2021-05-07 02:21 UTC, evaristor approved these changes

2021-05-07 02:21 UTC, merged