🎉 Agrega resumen sobre el manual de curación de datos
IslasGECI/islasgeci.github.io pull request #70
Opened 2021-05-07 19:32 UTC by MaritzaB

Como un primer paso para documentar nuestro manual de curación en el manual de procedimientos de CD, agregué el resumen del [manual de curación](https://docs.google.com/document/d/1A1JZQY_CZ0d_Mb_LW7WKS8r9ulPp6QvijFYbGCzR2yo/edit#heading=h.30j0zll).

2021-05-12 02:30 UTC, evaristor requested changes
Por favor podrías renombrar este archivo a `index.md`?

2021-05-12 21:03 UTC, MaritzaB commented
> ¿Por favor podrías agregar el archivo `manual_curacion/index.md` o renombrar `manual_curacion/resumen.md` a `manual_curacion/index.md`?

Claro que si, lo renombre a `index.md` 😄

2021-05-12 21:49 UTC, evaristor requested changes

2021-05-12 21:49 UTC, evaristor commented on manual_curacion/index.md
> +# Manual de Curación de Datos
El título se mostrará dos veces ya que se encuentra como metadato (`title: Manual de curación de datos`) y como H1 `# Manual de Curación de Datos`. Podemos quitarlo o reemplazarlo.

Opción 1:


```suggestion
```

Opción 2:

```suggestion
# Resumen
```

2021-05-12 21:58 UTC, evaristor requested changes

2021-05-12 21:58 UTC, evaristor commented on manual_curacion/index.md
> +
```suggestion

```

2021-05-18 17:14 UTC, evaristor approved these changes

2021-05-18 17:14 UTC, merged