✍️ Add blog post about LaTeX and Git
IslasGECI/islasgeci.github.io pull request #72
Opened 2021-05-18 19:16 UTC by evaristor

2021-05-19 17:54 UTC, nepito commented
Ya empecé y este comentario desde el Kraken. Lo malo es que no autocompleta los nombres, para poderte etiquetar @evaristor

2021-05-20 19:04 UTC, evaristor commented
Gracias @nepito

2021-06-03 16:22 UTC, nepito requested changes

2021-06-03 16:22 UTC, nepito commented on _posts/2021-05-18-latex_git.md
> +
Esta es la respuesta que da [GitHub](https://guides.github.com/activities/hello-world/#what) a esta pregunta.
```suggestion

GitHub es una plataforma de alojamiento de código para el control de versiones y la colaboración. Nos permite trabajar con otras personas juntos en proyectos desde cualquier lugar.

```

2021-06-10 21:23 UTC, nepito requested changes
@evaristor solo tengo un comentario, pero no estoy seguro de la sugerencia que hice.

2021-06-10 21:23 UTC, nepito commented on _posts/2021-05-18-latex_git.md
> +recibamos revisiones más claras. Cada PR solo nos muestra las secciones que hemos modificado,
Algo me suena extraño del segundo enunciado. Tal vez podríamos mejorarla de la siguiente manera:
```suggestion
Para solicitar revisión creamos un PR. En los PR de GitHub encontramos herramientas para que 
las revisiones que recibamos sean más claras. Cada PR solo nos muestra las secciones que 
hemos modificado,
```

2021-06-10 22:52 UTC, nepito approved these changes
Listo @evaristor voy aceptar el este PR.

2021-06-10 22:53 UTC, merged

2021-06-10 22:58 UTC, evaristor commented
Gacias @nepito