👷Crea archivo catalogo de voluntariados
IslasGECI/islasgeci.github.io pull request #73
Opened 2021-05-20 18:51 UTC by marthapaolajm

2021-05-26 15:32 UTC, evaristor commented on _posts/2021-05-20-catalogo_voluntariados.md
> +<img src="https://user-images.githubusercontent.com/77699134/119538077-97a9a980-bd3f-11eb-979e-a1d378b299df.png" width=150/>
Por favor podrías usar Gravatar?

```suggestion
<img src="https://www.gravatar.com/avatar/4ef11372a9af32065fd2893c32e93f1e?s=150">
```

2021-05-26 15:34 UTC, evaristor commented on _posts/2021-05-20-catalogo_voluntariados.md
> +      <img src="https://user-images.githubusercontent.com/77699134/119538210-bb6cef80-bd3f-11eb-9149-b62f57fea43b.png"width=150> </img>
¿Por favor podrías usar Gravatar?

```suggestion
      <img src="https://www.gravatar.com/avatar/c1c4f3ec6f19a0ee62ba529f5daaade0?s=150"> </img>
```

2021-05-26 15:38 UTC, evaristor commented on _posts/2021-05-20-catalogo_voluntariados.md
> +    <li>Andrea Sánchez Martínez
Cuando usamos Markdown algunos elementos de HTML, por ejemplo `<ul>`, `<li>`. En lugr de eso podrías usar simplemente un guión  `-`.

```suggestion
## Andrea Sánchez Martínez
```

2021-05-26 15:39 UTC, evaristor commented on _posts/2021-05-20-catalogo_voluntariados.md
> +<li>Martha Paola Jiménez Martínez
Cuando usamos Markdown algunos elementos de HTML, por ejemplo `<ul>`, `<li>`. En lugr de eso podrías usar simplemente un guión  `-`.

```suggestion
## Martha Paola Jiménez Martínez
```

2021-06-01 05:14 UTC, andrea-sanchez reviewed
¡Hallo Marthaaaaa! Dejé una línea para modificar, si por favor la pudieras consignar, lo agradecería.

Btw, Feliz Día del Matemático (en México jeje) 🥳

2021-06-01 05:14 UTC, andrea-sanchez commented on _posts/2021-05-20-catalogo_voluntariados.md
> +utilizadas dentro del equipo. Los resultados de mi proyecto se encuentran en GitHub.
```suggestion
utilizadas dentro del equipo. Los resultados de este proyecto se encuentran el [repositorio de Dimorfismo en GitHub](https://github.com/IslasGECI/dimorfismo).
```

2021-06-01 17:25 UTC, marthapaolajm commented on _posts/2021-05-20-catalogo_voluntariados.md
> +utilizadas dentro del equipo. Los resultados de mi proyecto se encuentran en GitHub.
¡Claro, muchas gracias!
Y feliz día para ti tambien✨

2021-06-02 16:58 UTC, nepito requested changes
Hola @marthapaolajm aquí te dejo mí revisión

2021-06-02 16:58 UTC, nepito commented on _posts/2021-05-20-catalogo_voluntariados.md
> +de Laysan en Isla Guadalupe”. Durante el proyecto no sólo enriquecí conocimientos bio-estadísticos,
Siento que falta un **mis**, pero no estoy seguro. Cuando cambio por el verbo perfeccionar me hace pensar que si no agregamos el **mis** suena muy general, como lo que diría un premio novel en su discurso de en la ceremonia en la que le entregan el premio: "No solo desarrollé los conocimientos en mecánica cuántica relativista logrando unir la relatividad general y con el modelo estándar sino en el camino logré erradicar el hambre mundial...". En cambio si agregamos el **mis** me parece más humilde: "Después del proyecto de vinculación mi entendimiento de la bio-estadística  a mejorado, ahora ya sé calcular promedios". 

¿Qué te parece el siguiente cambio?
```suggestion
de Laysan en Isla Guadalupe”. Durante el proyecto no sólo enriquecí mis conocimientos en bio-estadística,
```

2021-06-02 16:58 UTC, nepito commented on _posts/2021-05-20-catalogo_voluntariados.md
> +la población de cormorán en las islas del Pacifico”. Durante mi voluntariado desarrollé mis
Es difícil de distinguir, pero creo que le falta una tilde a Pacífico:
```suggestion
la población de cormorán en las islas del Pacífico”. Durante mi voluntariado desarrollé mis
```

2021-06-03 16:13 UTC, marthapaolajm commented on _posts/2021-05-20-catalogo_voluntariados.md
> +de Laysan en Isla Guadalupe”. Durante el proyecto no sólo enriquecí conocimientos bio-estadísticos,
Estoy de acuerdo contigo Nepo, el mis se escucha mejor!

2021-06-03 16:15 UTC, marthapaolajm commented on _posts/2021-05-20-catalogo_voluntariados.md
> +la población de cormorán en las islas del Pacifico”. Durante mi voluntariado desarrollé mis
Sí, de hecho cuando vi el cambio no note diferencia; pero ya leyendo tu comentario si, tienes toda la rayon ¡Muchas gracias!

2021-06-03 19:41 UTC, evaristor requested changes
![You got this!](https://media.giphy.com/media/l4FGvTHYa4vTqu3L2/giphy.gif)

2021-06-03 19:41 UTC, evaristor commented on _posts/2021-05-20-catalogo_voluntariados.md
> +
Aquí podríamos borrar los espacios innecesarios:

```suggestion

```

2021-06-03 19:41 UTC, evaristor commented on _posts/2021-05-20-catalogo_voluntariados.md
> +Dimorfismo](https://github.com/IslasGECI/dimorfismo) en GitHub.
¿Por favor podríamos mantener las líneas con una longitud menor o igual a 100 caracteres?

```suggestion
de Laysan en Isla Guadalupe”. Durante el proyecto no sólo enriquecí mis conocimientos en
bio-estadística, sino también, estudié y puse en práctica herramientas y técnicas computacionales
avanzadas utilizadas dentro del equipo. Los resultados de este proyecto se encuentran en el
[repositorio de Dimorfismo](https://github.com/IslasGECI/dimorfismo) en GitHub.
```

2021-06-03 19:41 UTC, evaristor commented on _posts/2021-05-20-catalogo_voluntariados.md
> +
Aquí podríamos borrar el espacio innecesario:

```suggestion

```

2021-06-04 02:33 UTC, andrea-sanchez reviewed
Pretty, pretty, pretty good! 🥳  Algo que les gustaría que agregara o alguna idea que profundice más? @marthapaolajm @nepito 

Pd. Deje un comentario _baby_, cuando tengas chance lo vemos por Slack porque no estoy taaan segura sobre el uso de las mayúsculas

2021-06-04 02:33 UTC, andrea-sanchez commented on _posts/2021-05-20-catalogo_voluntariados.md
> +Mi nombre es Martha Paola Jiménez Martínez y soy estudiante de la licenciatura en Matemáticas
Deberíamos ponernos de acuerdo con el uso de mayúsculas, para que quede re-chulo al final. Por ejemplo, yo usé mayúsculas en Licenciatura y Aplicadas pero no usé en Proyecto ¿Qué opinas?

2021-06-04 14:29 UTC, evaristor commented on _posts/2021-05-20-catalogo_voluntariados.md
> +Mi nombre es Martha Paola Jiménez Martínez y soy estudiante de la licenciatura en Matemáticas
Buena observación @andrea-sanchez 👍🏾

2021-06-04 19:49 UTC, marthapaolajm commented on _posts/2021-05-20-catalogo_voluntariados.md
> +Dimorfismo](https://github.com/IslasGECI/dimorfismo) en GitHub.
¡Sí claro!

2021-06-04 20:23 UTC, marthapaolajm commented on _posts/2021-05-20-catalogo_voluntariados.md
> +Mi nombre es Martha Paola Jiménez Martínez y soy estudiante de la licenciatura en Matemáticas
Sí, estoy totalmente de acuerdo. Agregue la mayúscula en Licenciatura,  Aplicadas y quite la mayúscula en proyecto, para que estén acorde!✨

2021-06-04 20:31 UTC, evaristor approved these changes
![Success](https://media.giphy.com/media/nXxOjZrbnbRxS/giphy.gif)

2021-06-04 20:34 UTC, merged

2021-06-04 20:41 UTC, evaristor commented
Muchas gracias @marthapaolajm y @andrea-sanchez