🚀 Lanzamiento ordinario
IslasGECI/islasgeci.github.io pull request #76
Opened 2021-06-23 22:31 UTC by evaristor

2021-06-24 03:00 UTC, nepito requested changes
Listo 😉

2021-06-24 14:16 UTC, evaristor commented on _posts/2021-06-23-tdd_mutants.md
> +
Sí está raro. No sé que onda.

2021-07-01 20:31 UTC, MaritzaB commented
Aprovechamos esta rama para agregar nuestra lista de reproducción de videos de Youtube relacionada a bases de datos ✌🏽 .

2021-07-26 16:10 UTC, MaritzaB approved these changes

2021-07-26 16:14 UTC, MaritzaB commented
Looks good to me
![image](https://user-images.githubusercontent.com/56838850/127022963-3631ea85-b07b-4385-b7c5-d98fd5290197.png)

2021-07-26 16:27 UTC, merged

2021-07-26 16:39 UTC, devarops commented
Gracias, @MaritzaB