Agrega entrada sobre Vim, tmux y QMK
IslasGECI/islasgeci.github.io pull request #80
Opened 2021-11-11 23:49 UTC by devarops

2021-11-12 21:17 UTC, nepito requested changes
Hola @devarops aquí te dejo mis comentarios

2021-11-12 21:17 UTC, nepito commented on _posts/2021-11-09-trifecta.md
> +QMK es posible mover las taclas más usadas en Vim y tmux a lugares más cómodos. Por ejemplo, la
Error de dedo:
```suggestion
QMK es posible mover las teclas que más usamos en Vim y tmux a lugares más cómodos. Por ejemplo, la
```

2021-11-12 21:17 UTC, nepito commented on _posts/2021-11-09-trifecta.md
> +Quienes pregonan el uso de estas herramientas argumentan que estas herramientas son mas eficientes
Error de dedo:
```suggestion
Quienes pregonan el uso de estas herramientas argumentan que éstas son más eficientes
```

2021-11-12 21:17 UTC, nepito commented on _posts/2021-11-09-trifecta.md
> +Vim es un editor de texto con una interfaz de texto que corre en la terminal de comandos del sistema
Aquí usamos dos veces la palabra texto muy seguido ¿habrá la manera de cambiar alguna de las dos?

2021-11-12 21:18 UTC, devarops commented
@nepito Muchas gracias por tu amable revisión

2021-11-12 21:20 UTC, devarops commented on _posts/2021-11-09-trifecta.md
> +Quienes pregonan el uso de estas herramientas argumentan que estas herramientas son mas eficientes
Creo que las nuevas reglas proponen que dejemos de usar la tilde en "éstas".

2021-11-12 21:26 UTC, devarops commented on _posts/2021-11-09-trifecta.md
> +Vim es un editor de texto con una interfaz de texto que corre en la terminal de comandos del sistema
Listo

2021-11-12 21:28 UTC, devarops commented
@nepito ¿Por favor me podrías revisar esto nuevamente?

2021-11-12 21:39 UTC, devarops commented
@nepito:

- [Renderizado](https://github.com/IslasGECI/islasgeci.github.io/blob/feature/vim_tmux_qmk/_posts/2021-11-09-trifecta.md)

2021-11-16 23:01 UTC, nepito approved these changes
Muchas gracias por atender por atender los comentarios. 
LGFM

2021-11-16 23:04 UTC, merged

2021-11-16 23:04 UTC, devarops commented
Muchas gracias, @nepito