💬 Add blogpost about an error in devcontainer
IslasGECI/islasgeci.github.io pull request #95
Opened 2022-03-15 17:19 UTC by AlejandroPad

2022-03-15 17:35 UTC, devarops requested changes
Tres ingredientes para la revisión de la prosa:


- [ ] Oraciones preferentemente <25 palabras (estrictamente <30 palabras)
- [ ] Concordancia entre sujeto y verbo
- [ ] Voz activa

2022-03-18 00:25 UTC, devarops requested changes
@AlejandroPad Aquí te dejo una primer tanda de comentarios.

Ya se lee mucho mejor 👍🏾

2022-03-18 00:25 UTC, devarops commented on _posts/2022-03-08-devcontainer_workdir.md
> +**devcontainer**.
Los nombres de archivos los ponemos entre _backtick_:

```suggestion
`.devcontainer/devcontainer.json`.
```

2022-03-18 00:25 UTC, devarops commented on _posts/2022-03-08-devcontainer_workdir.md
> +```bash
Aquí en lugar de _bash_ tal vez convenga usar _json_

2022-03-18 00:25 UTC, devarops commented on _posts/2022-03-08-devcontainer_workdir.md
> +Con la opción `workspaceMount` le decimos al vscode que vincule nuestro directorio local en la
```suggestion
Con la opción `workspaceMount` le decimos al VS Code que vincule nuestro directorio local en la
```

2022-03-18 00:25 UTC, devarops commented on _posts/2022-03-08-devcontainer_workdir.md
> +Ahora tenemos que borrar los contenedores porque puede que vscode los vuelva a utilizar al
```suggestion
Ahora tenemos que borrar los contenedores porque puede que VS Code los vuelva a utilizar al
```

2022-03-18 00:25 UTC, devarops commented on _posts/2022-03-08-devcontainer_workdir.md
> +vscode.
```suggestion
VS Code.
```

2022-03-18 00:25 UTC, devarops commented on _posts/2022-03-08-devcontainer_workdir.md
> +```
Aquí sí podrías usar _shell_ al final del triple _backtick_.

2022-03-18 00:25 UTC, devarops commented on _posts/2022-03-08-devcontainer_workdir.md
> +$ docker ps -a
Cuando trabajamos en la terminas sí usamos las opciones cortas, pero cuando documentamos usamos la forma larga:

```suggestion
$ docker ps --all
```

2022-03-18 00:25 UTC, devarops commented on _posts/2022-03-08-devcontainer_workdir.md
> +La opción `-a` nos muestra todos los contenedores.
Cuando trabajamos sí usamos las opciones cortas, pero cuando documentamos usamos la forma larga:

```suggestion
La opción `--all` nos muestra todos los contenedores.
```

2022-03-18 00:25 UTC, devarops commented on _posts/2022-03-08-devcontainer_workdir.md
> +$ docker ps -aq
Cuando trabajamos sí usamos las opciones cortas, pero cuando documentamos usamos las formas largas:

```suggestion
$ docker ps --all --quiet
```

2022-03-18 00:25 UTC, devarops commented on _posts/2022-03-08-devcontainer_workdir.md
> +$ docker rm $(docker ps -aq)
```suggestion
$ docker rm $(docker ps --all --quiet)
```

2022-03-18 00:25 UTC, devarops commented on _posts/2022-03-08-devcontainer_workdir.md
> +La instrucción `rm` remueve los contenedores.
```suggestion
El subcomando `docker rm` remueve los contenedores.
```

2022-03-18 00:25 UTC, devarops commented on _posts/2022-03-08-devcontainer_workdir.md
> +Ya habiendo realizado esto, puedes volver a abrir el contenedor en vscode y estará resuelto el
```suggestion
Ya habiendo realizado esto, puedes volver a abrir el contenedor en VS Code y estará resuelto el
```

2022-03-18 00:25 UTC, devarops commented on _posts/2022-03-08-devcontainer_workdir.md
> +problema: nuestro directorio de trabajo será **/workdir**
```suggestion
problema: nuestro directorio de trabajo será `/workdir/`
```

2022-03-18 00:25 UTC, devarops commented on _posts/2022-03-08-devcontainer_workdir.md
> +```
Aquí puedes agregar _shell_ al final del triple _backtick_.

2022-03-18 00:25 UTC, devarops commented on _posts/2022-03-08-devcontainer_workdir.md
> +```bash
Cambia _bash_ por _shell_ al final del triple _backtick_.

2022-03-18 00:25 UTC, devarops commented on _posts/2022-03-08-devcontainer_workdir.md
> +```bash
Aquí tal vez convebga quitar el _bash_ al final del triple _backtick_ ya que esto no es un comando.

2022-03-18 00:25 UTC, devarops commented on _posts/2022-03-08-devcontainer_workdir.md
> +/workspaces/sub-folder
```suggestion
/workspaces/repositorio
```

2022-03-18 00:25 UTC, devarops commented on _posts/2022-03-08-devcontainer_workdir.md
> +Dentro de **.devcontainer/devcontainer.json** agregaremos:
Los nombres de los archivos los ecribimos entre _backticks_ simples.
```suggestion
Dentro de `.devcontainer/devcontainer.json` agregaremos:
```

2022-03-29 17:32 UTC, devarops requested changes
- [ ] Mejora el título agregando un verbo
- [ ] Agrega párrafo introductorio
- [ ] Agrega mensaje de error

2022-04-26 16:00 UTC, nepito approved these changes
LGTM

2022-04-26 16:03 UTC, merged